Draft: Add channel packer tool
TokisanGames/Terrain3D pull request #259
Opened 2023-11-28 04:41 UTC by epitaque

Needs testing.
Closes #125 .

Incorporates the following feedback:

> Cory [Tokisan] — Regarding your channel packing panel, @Lorenz is creating a [tools menu](https://github.com/TokisanGames/Terrain3D/issues/81). Once that's done you can add a menu option that will open up a panel for your channel packer. 

It should provide filename fields with a directory button that opens up the godot file selector so they can pick their maps, and specify the output file name with little typing. Texture files rarely have the same naming convention. They could have tags like _albedo, _alb, _basecolor, _bc, _diffuse, _diff or hyphens or no tag at all, or have the resolution at the end.

Other tools will be in Windows. This could open a popup window. If you go with a dock, it will be inconsistent with other tools, but it will mean people can drag and drop files into the file slots. 🤔  I think a popup window is better. We'll likely integrate all tools into a single window in the future, and with the directory buttons they can easily click to their files. 

Only exporting PNG is fine. 

You should provide enough fields for all 4 files to be processed into 2 output files at once. But also work if they only fill in one set.

![image](https://github.com/TokisanGames/Terrain3D/assets/7350617/a099cace-eac3-4400-9e2b-3ad0486f7dbb)
![image](https://github.com/TokisanGames/Terrain3D/assets/7350617/9491344c-3b88-4b3d-bc95-83feae210d89)

2023-11-28 05:12 UTC, epitaque commented
Todo:

- [ ] Save file dialog does not start in the correct directory (right now, it's starting in the root directory. Kind of a pain to navigate through your project.)
- [ ] I experienced a crash when packing a 2048x2048 texture. Have not had it happen since, but maybe test it a few more times? And also see if 4k works. There is a big lag spike since we're setting every pixel in a GDScript double for loop.
- [ ] When the Terrain3D plugin is disabled we should probably destroy the window.

2023-11-28 05:54 UTC, TokisanGames commented
Good start. This isn't a full review, just some initial notes.

> Save file dialog does not start in the correct directory (right now, it's starting in the root directory. Kind of a pain to navigate through your project.)

* It should start in the project root folder, but be able to navigate the full file system. On subsequent clicks, it should open up in the last used directory.

> And also see if 4k works

Godot supports 16k x 16k Images and Textures.


> There is a big lag spike since we're setting every pixel in a GDScript double for loop.

* This is a gdextension, so writing all components in C++ is ideal. At the least, pack_textures can go in Util, which could be exposed as Terrain3DUtils.

* If `Pack` opens up a Save File Dialog, the button should have `...` appended. But clearer would be, `Pack textures as...`
You also need a cancel / close button.

* Please add text labels at the top describing what this does and how they should use it.

* The file box can be reduced to 50-70%. It looks odd being so wide.

* Each label should have texture appended "Albedo texture"

2023-11-28 06:01 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +var window_scene: PackedScene = preload("res://addons/terrain_3d/editor/components/channel_packer.tscn")
Don't do this with resources and scenes. Preload sucks; it loads all of them everywhere on engine start.

Do this:
https://github.com/TokisanGames/Terrain3D/blob/c5a72b0b7aa843e925c8f39760fb74b314c5bd4d/project/addons/terrain_3d/editor/components/tool_settings.gd#L22
https://github.com/TokisanGames/Terrain3D/blob/c5a72b0b7aa843e925c8f39760fb74b314c5bd4d/project/addons/terrain_3d/editor/components/tool_settings.gd#L261

or `instantiate(load(SCENE))`

2023-11-28 06:01 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +func _on_SaveFileDialog_file_selected(dst_path):
Functions should all be lower case and static typed

2023-11-28 06:03 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +	file_dialog.connect("file_selected", _on_SaveFileDialog_file_selected)
`file_dialog.file_selected.connect(_on_SaveFileDialog_file_selected)` is superior as it allows the static checker to check your code. Fix elsewhere.

2023-11-29 02:03 UTC, epitaque commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +	file_dialog.connect("file_selected", _on_SaveFileDialog_file_selected)
Should be done!

2023-11-29 02:12 UTC, epitaque commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +func _on_SaveFileDialog_file_selected(dst_path):
Done.

2023-11-29 02:12 UTC, epitaque commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +	file_dialog.connect("file_selected", _on_SaveFileDialog_file_selected)
Done.

2023-11-29 02:12 UTC, epitaque commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +var window_scene: PackedScene = preload("res://addons/terrain_3d/editor/components/channel_packer.tscn")
Done.

2023-12-01 11:24 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +const IMPORT_INSTRUCTIONS: String = "In the Godot Editor, please:\n1. Select texture in the FileSystem. \n2. Go to the Import tab and make sure the texture is imported as VRAM Compressed."
List the consts first, then a blank line, then plugin and the other vars

2023-12-01 11:25 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +	var base_control = EditorInterface.get_base_control()
We're not ready to not support 4.1 yet. EditorInterface is not static yet. For now you can do:
`var editor_interface: EditorInterface = plugin.get_editor_interface()`

Also static type base_control.

2023-12-01 11:41 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +	var picker = EditorResourcePicker.new()
Static type all variables. There are many that are not. Here only you can use `:=` because it says the name right next to it. Every other variable needs to be static typed. Every function needs static typed parameters and return variable.

2023-12-01 11:42 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +func show_error(text: String) -> void:
Add a `p_` prefix on all function parameters. I just went through and added it everywhere it was missing.

2023-12-01 11:43 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +	print("ChannelPacker Success: " + text)
Preface with "Terrain3DChannelPacker: " then, "Texture creation successful." or whatever

2023-12-01 12:14 UTC, TokisanGames commented
Ok, good progress. Thanks for the iteration.

We need to support 4.1 for the time being. The editorinterface thing I mentioned will get it running.

I loaded it in 4.1.3, and since there's no option to load textures outside of my project, I moved them in to the project folder. I pulled in 4 2k jpg files for the [demo grass](https://ambientcg.com/view?id=Ground037).

* Upon loading the tool, first I saw a flash on my left monitor as if the window opened there and then was moved over. The other Terrain tools popups don't do this. Change the Absolute initial position in the Window settings to Center of Primary screen.

* I got a malformed looking window. It's quite long. It's probably a 4.1/4.2 thing

![image](https://github.com/TokisanGames/Terrain3D/assets/632766/534380dd-7cc1-48c4-a172-fce4207edcdf)

* Quickload and load worked fine to pull in my images from the project folder. However, I can't access the files outside. It's far more likely that someone will store master textures outside of their project file, load them up here, and save the combined file here in the project folder. Please enable loading images from anywhere.

* Upon packing as, I named the png and then I got this spammed to my console thousands of times until I forced Godot to close. Not sure why this occurs, you'll need to look into it. There is `Image.is_compressed()`. Let me know if you need help. You may also need to convert Images, or get Images from Textures, as someone may want to load their DDS, exr, png, jpg, bmp, or [any format godot supports](https://docs.godotengine.org/en/stable/tutorials/assets_pipeline/importing_images.html#supported-image-formats)

```
ERROR: Can't get_pixel() on compressed image, sorry.
   at: (core/io/image.cpp:3163)
```

* Before packing, I also get this error message many times under general usage, opening and closing the window:
```
ERROR: Signal 'tree_exited' is already connected to given callable 'Object(channel_packer.gd)::_on_close_requested' in that object.
   at: (core/object/object.cpp:1294)
```

* Please add a cancel button, and make sure Escape triggers it.

* Tom made changes to the tools menu. Please rebase and make sure you get inserted properly into it. And greyed out when a navigationregion3d is selected (open NavigationDemo and click the navregion).

* You could provide an option to resize textures here. I would print the image size of each once you selected it. Then I'd include a checkbox to resize, with a dropdown of square powers of 2: 256, 512, 1024, 2048, 4096, 8192, 16384). Then I'd run all images through Image.resize before packing. This can also come in a later PR if you don't want to add it now.

I'm unable to test further since the above breaks. But this should give you some more to work on for now. My next steps would have been trying different input file types that people will use and see what it does with them.

2023-12-04 17:18 UTC, epitaque commented
Hey, sorry you encountered all those issues. 

Re the image picking stuff: I was using Godot's EditorResourcePicker for the texture inputs, which was great, but also limits the user to images in the project. I agree, it would be nice to pick images outside the project. 

I'll work on switching it over to a file dialog as well as those other issues you mentioned.

2023-12-08 06:42 UTC, epitaque commented
Completed most of the items, but am not completely done. Todo:
- gray out the menu when a navigationregion3d is selected
- refactor the gdscript a bit. It's not the prettiest, may be able to get rid of some state.
- fix the formatting
- add that check in the cpp code

Unsure about dds support being feasible. I'll have to do more research. I think you'd want to use the source images (used to make the dds) anyway, no? DDS is lossy.

2023-12-08 06:58 UTC, TokisanGames commented
DDS, jpg, and other lossy formats _shouldn't_ be used, but sometimes that's all you have. We should support reading anything Godot can read, and writing to png unless they start offering writing to dds/ktx.

2023-12-09 04:20 UTC, TokisanGames commented
You should include a checkbox that inverts (1-x) the green channel so they can convert directx normal maps to opengl.

2023-12-14 06:15 UTC, epitaque commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +func pack_textures_popup():
Done.

2023-12-14 06:15 UTC, epitaque commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +	var base_control = EditorInterface.get_base_control()
Done.

2023-12-14 06:15 UTC, epitaque commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +	picker.base_type = "Texture2D"
Not using EditorResourcePicker anymore.

2023-12-14 06:17 UTC, epitaque commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +	var picker = EditorResourcePicker.new()
Done (except for lambdas, I don't know how to static type those.)

2023-12-14 06:17 UTC, epitaque commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +func show_error(text: String) -> void:
Done.

2023-12-14 06:18 UTC, epitaque commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +	print("ChannelPacker Success: " + text)
Done.

2023-12-14 06:18 UTC, epitaque commented on project/addons/terrain_3d/editor/components/channel_packer.tscn
> +title = "Channel Packer Tool"
Done.

2023-12-14 06:35 UTC, epitaque commented
So some things:
- I tested it on Godot 4.1, it works now.
- I tried finding a valid .dds file via google - could not find anything. @TokisanGames (or anyone) - could you share a sample .dds texture so I can see if this tool can pack it?
- I think I got all of the issues in here are resolved. The windowing stuff is all fine on my end - but I could definitely still be doing something wrong and it could look different on your PC, in which case I'll be happy to take another look.

<img src="https://github.com/TokisanGames/Terrain3D/assets/7350617/e30e69ab-f84b-4cbe-b178-64879453a315" width=50%>

2023-12-26 11:25 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.tscn
> +ok_button_text = "Close"
This point wasn't addressed:
* Upon loading the tool, first I saw a flash on my left monitor as if the window opened there and then was moved over. The other Terrain tools popups don't do this. Change the `initial_position` in the Window settings from `Absolute` to `Center of Primary Screen`.

2023-12-26 11:36 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.tscn
> +(Use if normal texture is DirectX style)"
Please make this checkbox a child of `NormalVBOX` so it appears inside. Then change the label text to:
`Convert DirectX to OpenGL`.

2023-12-26 11:54 UTC, TokisanGames commented on src/util.cpp
> +/* From source RGB and R channels, create a new RGBA image. If invert_green_channel is true,
"and A channels"

2023-12-26 11:55 UTC, TokisanGames commented on src/util.cpp
> +	}
This block needs to be first. If they are not valid, then any dereference `src_rgb->func()` will crash Godot.

2023-12-26 13:07 UTC, TokisanGames requested changes
This is looking better and getting there. I tested this in 4.1.3 and had these notes:

* The paint brush icon is odd for clear. Is there a better alternative, like an X or slash or trash? The folder icon is great.

* The dialog filter doesn't work. I clicked the open and went to a folder with jpgs I downloaded and it showed empty on `all recognized`. Changing to jpg also doesn't show. If I change to all files, it shows the jpgs. You have `*.png` but all the others are `.jpg`.

![image](https://github.com/TokisanGames/Terrain3D/assets/632766/5dd985bb-269f-4872-b557-36c963667c91)


* If I open the packer, then close it, on subsequent opens, when I click any file open the first time, I get this error on the console and some things stop working like normal texture creation, or retaining the same directory.
```
ERROR: Attempt to disconnect a nonexistent connection from '@FileDialog@21051:<FileDialog#2590653896073>'. Signal: 'file_selected', callable: '<anonymous lambda>(lambda)'.
   at: (core/object/object.cpp:1351)
```

* I loaded up 4 textures and packed them. It prompted me for a filename and saved the albedo_height texture. It did nothing with the normal/roughness. Is it your intention that they will do it twice, using the top options the first time and the bottom options the second? That is confusing. It should just be a single set of rgb and alpha textures instead of albedo/height, normal/roughness. Or better, it should open up the dialog twice so they can save each pair of textures, if they are not null.


* When you save a file, also create a `.import` file in the same folder. Write this text to the file, changing only the filename of `source_file`. Godot will fill in the rest. This will automatically setup the file as vram compressed, normal maps disabled, and mipmaps enabled.

```
[remap]

importer="texture"
type="CompressedTexture2D"
metadata={
"imported_formats": ["s3tc_bptc"],
"vram_texture": true
}

[deps]

source_file="res://packed_albedo_height.png"

[params]

compress/mode=2
compress/high_quality=false
compress/lossy_quality=0.7
compress/hdr_compression=1
compress/normal_map=2
compress/channel_pack=0
mipmaps/generate=true
mipmaps/limit=-1
roughness/mode=0
roughness/src_normal=""
process/fix_alpha_border=true
process/premult_alpha=false
process/normal_map_invert_y=false
process/hdr_as_srgb=false
process/hdr_clamp_exposure=false
process/size_limit=0
detect_3d/compress_to=1

```

2024-01-12 07:17 UTC, epitaque commented
Alright, it should be good now, but that's what I said last time. Will do a thorough test later then mark ready, though feel free to test now if you have time.

2024-01-28 12:55 UTC, TokisanGames commented
Generally I won't review until you say it's ready. But your last message said it both should be good and you'll test and mark ready. So I'll look at it again within a few days.

2024-01-28 21:47 UTC, epitaque commented
I thoroughly tested this and believe it's ready for your review. I think it's very user-friendly now, I made a few minor changes that make a world of difference (being able to click the texture previews to open a file picker + actually remembering the previous directory of the file picker, not the one above it). Let me know if you have any more comments - I will be much quicker about resolving them this time, I'd love to get this merged.

2024-01-29 15:47 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +const ROUGHNESS_IMAGE_INDEX: int = 3
Make this an enum

```
enum { 
  IMAGE_ALBEDO,
  IMAGE_HEIGHT,
  IMAGE_NORMAL,
  IMAGE_ROUGHNESS,
}
```

2024-01-29 15:54 UTC, TokisanGames commented on src/util.h
> +	static Ref<Image> pack_image(const Ref<Image> src_rgb, const Ref<Image> src_r, bool invert_green_channel);
* Preface all function parameters with `p_`.
* Assign a default value for invert green to `=false`

2024-01-29 15:56 UTC, TokisanGames commented on src/terrain_3d.cpp
> +	ClassDB::bind_static_method("Terrain3D", D_METHOD("pack_image", "src_rgb", "src_r", "invert_green_channel"), &Util::pack_image);
Add `DEFVAL(false)` like get_thumbnail.

2024-01-29 15:57 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/terrain_tools.gd
> +	MENU_PACK_TEXTURES
Leave a comma at the end for style. Enum can then be reordered without needing to remember to place the comma.

2024-01-29 16:09 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +func create_import_file(png_path: String):
static type return

2024-01-29 16:11 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +func _on_close_requested() -> void:
Move this func right below pack_textures_popup

2024-01-29 16:21 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +	(dialog.get_node(prefix + "PackButton") as Button).pressed.connect(_on_pack_button_pressed)
You only use prefix for this one line, so it doesn't need to be a global. I'd just insert the contents of prefix in here combined with packbutton.

2024-01-29 16:23 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +	var openFn = func():
Make open and clear camel case, and static type as `Callable`.

2024-01-29 16:23 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +var last_file_selected_fn = null
Static type as Callable

2024-01-29 16:33 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +	var clearFn = func():
add a blank line above, and strip out the empty lines within the above lambda so each is a compact block

2024-01-29 16:37 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +func wire_texture_picker(p_parent: Node, p_image_index: int) -> LineEdit:
wire is a strange name. Do you mean it as "wire up" or setup? I think `init_texture_picker` is better and consistent with the above function.

2024-01-29 16:38 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +	albedo_resource_picker = wire_texture_picker(dialog.find_child("AlbedoVBox"), ALBEDO_IMAGE_INDEX)
You aren't using these return values. Took me a while to figure out why you were returning LineEdits and the answer is no reason. Drop these variables, remove the return value, and just have this init function connect the signals.

2024-01-29 16:39 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +	return line_edit
As mentioned, the return here is not used or needed, so drop it and the class variables that get assigned.

2024-01-29 16:41 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +	status_label.add_theme_color_override("font_color", Color(232.0/256.0, 0, 0))
Setting to 0.9 is fine. Decimal colors are commonly used throughout. You can also convert the other uses.

2024-01-29 16:44 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +	var template_path: String = "res://addons/terrain_3d/editor/components/channel_packer_import_template.txt"
make this a capitalized const and place at the top.

2024-01-29 16:44 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +	var template_content = file.get_as_text()
static type

2024-01-29 16:45 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +	var import_content = template_content.replace("$SOURCE_FILE", png_path)
static type

2024-01-29 16:45 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +
2 blank lines

2024-01-29 16:46 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +	var _editor_base: Control = editor_interface.get_base_control()
remove `_`. We use a `_` prefix for private class variables, mostly in C++, but not much in gdscript. We should and will likely clean that up in the future. No need for it in a local var.

2024-01-29 16:51 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/channel_packer.gd
> +func _on_save_file_dialog_file_selected(p_dst_path) -> void:
rename to _on_save_file_selected

2024-01-29 17:01 UTC, TokisanGames commented
Ok good job. It works well and is very usable. I have a lot of style notes for you. Once those are addressed we can merge this in.

* I left notes to reorder some functions. The idea is that reading through the code I want a sense of the order of operations. As it is you have init_texture_picker,  pack_textures, _on_save_file_selected. But it would be clearer if the last is in the middle so I can read straight down the file, rather than jumping around. Obviously they can't all be right next to the function that calls them, so use best judgement and group them by context. eg. show_success and show_error should definitely be adjacent, and near where they were first called. Otherwise, I would put godot callable functions (_ready, _enter_tree, etc) at the top if you had any. Also look at baker.gd and all of the C++. Functions not intended to be called by others are prefaced with a `_`.  As are variables. We're strict with both on C++ but a bit lax in gdscript.

* DDS textures don't load. Remove the filter. Or you could look more into why not. Supporting DDS won't hold up this PR.

* In channel_packer.gd, which functions are private, and which are intended to be accessible to the public? Preface the private ones with `_` like the signal callbacks. Probably all but pack_textures_popup()

* In 4.2.1 channel_packer.tscn, I cannot select anything in the 2D viewport. But I don't see anything locked. Is there a feature enabled that prevents editing? I can edit in the scene tree and inspector.

Future improvements that can be addressed in a future PR:
* Display image size at bottom of each
* Add a convert smoothness to roughness checkbox under Roughness, which inverts it
* Above Pack button, add checkboxes for:
  *  Mipmap generation - Image::create_image
  * High quality - Import template: `compress/high_quality=true`
* Support reading DDS files

2024-01-30 05:28 UTC, epitaque commented
@TokisanGames Done! I removed .dds support for now.

2024-01-30 10:45 UTC, TokisanGames commented on src/util.h
> +	static Ref<Image> pack_image(const Ref<Image> src_rgb, const Ref<Image> src_r, bool invert_green_channel);
p_ should go here as well. 
= false should only go here.
I moved them.

2024-01-30 11:00 UTC, merged