Add terrain_edited signal to Terrain3DEditor
TokisanGames/Terrain3D pull request #274
Opened 2023-12-13 17:21 UTC by tcoxon

As discussed in #270.

Terrain3DEditor becomes a singleton, and gains a new `terrain_edited(edited_area: AABB)` signal. The use case is integration with other level design tools and scripts - see the linked issue.

The signal is emitted whenever:
- a region is added or removed,
- a region map is altered with a brush tool,
- or any of the above are undone / redone.

In the end I decided not to include the map_type parameter in the signal, as it seems like this would not be relevant to non-brush-related tools (region add/remove, etc.).

2023-12-26 09:52 UTC, TokisanGames commented on src/terrain_3d_editor.cpp
> +				}
This can be moved up to the map_type=height section after new line 248.

2023-12-26 09:59 UTC, TokisanGames commented on src/terrain_3d_editor.cpp
> +	_undo_set.resize(Terrain3DStorage::TYPE_MAX + 3);
Please add `5: edited AABB` in the function comment above, L386

2023-12-26 10:06 UTC, TokisanGames commented on src/terrain_3d_editor.cpp
> +	ADD_SIGNAL(MethodInfo("terrain_edited", PropertyInfo(Variant::AABB, "edited_area")));
Please add signal documentation (when it's fired in your PR description)

In `doc/classes/Terrain3DEditor.xml`, between `methods` and `constants` paste and fill out:
```
    <signals>
        <signal name="terrain_edited">
            <param index="0" name="edited_area" type="AABB" />
            <description>
            </description>
        </signal>
    </signals>
```

2023-12-26 10:07 UTC, TokisanGames requested changes
Why does this class need to be a singleton in order to fire a signal? Can't normal classes do that?

2024-01-01 19:09 UTC, tcoxon commented
> Why does this class need to be a singleton in order to fire a signal? Can't normal classes do that?

So that tool scripts and other addon scripts besides the Terrain3D addon can access it. Currently Terrain3DEditor is created and the reference held by the EditorPlugin, but other scripts can't access this.

2024-01-02 16:02 UTC, tcoxon commented
I've updated my branch to address your other comments.

2024-01-03 18:28 UTC, merged

2024-01-03 18:28 UTC, TokisanGames commented
Thanks!

2024-01-28 15:54 UTC, TokisanGames commented on src/terrain_3d_editor.cpp
> +	edited_area.position = p_global_position - Vector3(brush_size, 0.0, brush_size) / 2;
Shouldn't 2 be float just to avoid unnecessary conversions? I'm changing this in the new PR