Make collision generation dynamic
TokisanGames/Terrain3D pull request #278
Opened 2023-12-17 01:06 UTC by lw64

Fixes #161

2023-12-26 10:11 UTC, TokisanGames commented on project/demo/Demo.tscn
> +debug_show_collision = true
Please leave this disabled in the demo.

2023-12-26 10:15 UTC, TokisanGames commented on src/terrain_3d.cpp
> +	ADD_PROPERTY(PropertyInfo(Variant::BOOL, "dynamic_collision"), "set_dynamic_collision", "get_dynamic_collision");
This variable name broke the inspector group. It needs to begin with "collision_" to keep all of these in one group.

Instead, look at the last bullet point of #161 and make this and debug_show_collision one enum called `collision_mode` with the four listed meanings.

2023-12-26 10:29 UTC, TokisanGames commented on src/terrain_3d.cpp
> +					debug_col_shape = memnew(CollisionShape3D);
If you play this and watch your process monitor, the game continually consumes more and more memory as the player moves around. All memory allocation needs to be moved to `_build_collision` and all freeing moved to `_destroy_collision`.

2023-12-26 10:33 UTC, TokisanGames commented on src/terrain_3d.cpp
> +	float maximum_distance = 64.0;
This should also be a parameter. 
* Rename collision_region_size to collision_shape_size
* Rename maximum_distance to collision_distance 
* Make both settable variables accessible to gdscript

2023-12-26 10:37 UTC, TokisanGames commented on src/terrain_3d.cpp
> +		    RID shape = PhysicsServer3D::get_singleton()->body_get_shape(_static_body, i);
Rather than query the shapes from the server, just create an array with all of the predefined collision shapes in build_collision. Then empty the array in destroy_collision.

2023-12-26 10:54 UTC, TokisanGames commented on src/terrain_3d.cpp
> +						int z_in_region = z + jz * collision_region_size;
Throughout you are using `region` to refer to the collision shape. It's confusing to read and understand what these variables are for. Please go through and rename all of the variables you've added that reference your collision shapes. Call them something to do with `shape`. Use `region` only for things that deal with the entire 1024x1024 region. Here x_in_region is the x shape size, plus the shape global location. So it should be called `shape_global_x`.

2023-12-26 11:04 UTC, TokisanGames commented on src/terrain_3d.cpp
> +	int divisor = region_size / collision_region_size;
Divisor is the number of collision shapes of size 16x16 that fit in a region of size 1024x1024, or 64. So it should be named appropriately, eg `shapes_per_region`

2023-12-26 11:15 UTC, TokisanGames requested changes
Alright, good job. I think once the memory management is moved to build collision and destroy collision it will be on par or better than a single 65x65 collision shape. Worse because it has to manage 50-60 shapes, but better because it only needs to update a few smaller shapes instead of all 65x65.

We're pretty close. Make the modifications, rebase and it should be finished or very close.
Thanks!

2024-01-03 14:16 UTC, lw64 commented on src/terrain_3d.cpp
> +						map_data = shape_data["heights"];
I am not entirely sure this avoids allocations. But I also don't see another method. the map_data gets assigned back later again.

2024-01-03 14:18 UTC, lw64 commented on src/terrain_3d.cpp
> +						hshape = debug_col_shape->get_shape();
I implemented the chaching for both the debug and non-debug modes, but I don't know if that actually makes sense.

2024-01-03 14:21 UTC, lw64 commented on src/terrain_3d.cpp
> +					debug_col_shape = memnew(CollisionShape3D);
I couldn't move the memory allocation fully to `_build_collision`, as it is not defined at build time, how many collision shapes need to be allocated. the `distance` is variable, and for example for `64.0` the shape count varies between 48 and 52 in my experience, depending on the camera position.

2024-01-03 14:23 UTC, lw64 commented on src/terrain_3d.cpp
> +					debug_col_shape = memnew(CollisionShape3D);
I made it now allocate new ones on demand, but that should only happen during the first `_update_collision` call.

2024-01-03 15:19 UTC, lw64 commented
One thing I observed is that when you change the collision_mode from full to dynamic, the collision shapes aren't freed. But I guess its not a problem since this isn't changed at runtime. And in the editor you can just reopen the scene

2024-01-03 19:58 UTC, TokisanGames commented on src/terrain_3d.cpp
> +						map_data = shape_data["heights"];
The allocations and deallocations we want to avoid in update_collision are `memnew` and `memfree`. Creating a PackedFloat32Array here is fine. This gets created on the stack which is designed for frequent, rapid creation/destruction. The other two allocate memory on the heap, which should not be as frequent.

2024-01-03 22:18 UTC, TokisanGames commented
> I couldn't move the memory allocation fully to _build_collision, as it is not defined at build time, how many collision shapes need to be allocated.

* `Array.resize()` will resize arrays dynamically.
shapes_per_region is calculated in update_collision, but doesn't need to be, it can be calculated in build_collision.

* In game modes (physics server) are broken:
```
ERROR: Index p_index = 0 is out of bounds (shapes.size() = 0).
   at: set_shape (servers/physics_3d/godot_collision_object_3d.cpp:52)
ERROR: Index p_index = 0 is out of bounds (shapes.size() = 0).
   at: set_shape_transform (servers/physics_3d/godot_collision_object_3d.cpp:63)
```

* Three related issues don't rebuild collision properly. Upon set_collision_mode, set shape size, & distance it should destroy and build collision to free allocations and set everything up properly, just like set_collision_enabled does.
  * Changing from `Full editor` to `Dynamic editor` all collision meshes are huge and don't get resized down.

  * Changing shape size (on dynamic in editor mode) crashes godot.

  * Changing from an editor mode to a game mode does not remove the shapes, but should. 

I didn't evaluate all of the new code since there are things that aren't working. Let me know if you need help with anything or want to work on things together.

I added a PR that renames and organizes some things.

2024-01-13 14:18 UTC, lw64 commented on src/terrain_3d.cpp
> +					PhysicsServer3D::get_singleton()->body_set_shape_transform(_static_body, shape_id, xform);
The problem here is the shape id. There is no way to get the correct one added with `add()`, and the on I guessed using `shape_count` seems to be wrong.

2024-01-17 09:40 UTC, TokisanGames commented
In dynamic editor mode, collision shapes do not have unique positions and are doubling up

![image](https://github.com/TokisanGames/Terrain3D/assets/632766/64a01c58-71cb-43d9-a990-ef1fc9a60cdc)


Though this solution is an interesting method, I feel like this is an overly complicated solution. 

What I proposed was using a small 65x65 collision square around the player, then on every snap, update the vertices of the shape, so 4225 vertex updates every snap, (which is based on movement, not frames). That is how my [gterrain code](https://github.com/TokisanGames/gterrain/blob/570951f8fa16a94ea186df8ca3791fee5c984375/addons/gterrain/src/GTerrain.gd#L161) worked, and is very short and simple. It will work fine with the static body and physics server, and does not continually allocate and deallocate memory.

This solution has improves upon it by breaking down the collision shape into 17x17 vertex chunks, and only new chunks are updated. So when moving laterally, say 8 chunks are updated, or 2312 vertices updated.

The cost of it though is a rather complicated chunking system that needs to track 50-64 collision shapes and move them around accurately without making memory non-contiguous by constant allocations and deallocations. This hasn't been achieved quite yet, so additional cost is that we need to spend more time to preallocate all of the shapes in build_collision, and identify that shapes aren't doubling up. 

Then we have to maintain this code over time.

And the physics server needs to calculate based on 64 shapes instead of 1. 

Though I started working on this PR to clean up and fix things, once I discovered the doubling up, I think the scales tipped for me in the cost/benefit analysis. 

I'm not sure the added overhead of us and the physics server managing all of the extra shapes, and the effort we've put in and still need to put in is worth the savings of ~2000 vertex assignments per snap. Whether it's 2000 or 4000 adjustments, both are inconsequential.

I think we should revert most of these changes and go back to the simpler solution proposed in #161 and demonstrated in my [gterrain code](https://github.com/TokisanGames/gterrain/blob/570951f8fa16a94ea186df8ca3791fee5c984375/addons/gterrain/src/GTerrain.gd#L161). Though the editor collision modes and settable collision shape size are good.

What do you think?

2024-01-17 19:08 UTC, lw64 commented
So I addressed your issue with the doubled collision shapes and its fixed now. Also I finished the non-editor collision, which was previously not really done yet. The issues I had before with missing API was resolved by finding the correct API xD I tested this a bit and for me it doesn't leak any memory and there shouldn't be any allocations as far as I can see. So I think its good to go now.

2024-01-17 19:09 UTC, lw64 commented on src/terrain_3d.cpp
> +						map_data = shape_data["heights"];
Which other two? `Dictionary`?

2024-01-17 20:14 UTC, TokisanGames commented on src/terrain_3d.cpp
> +						map_data = shape_data["heights"];
By other two, I mean the general usage of memnew and memfree. Not referring to lines specifically.

2024-01-19 12:14 UTC, TokisanGames commented
Alright, I tested more and now it's all working well. Good job. There are a few more improvements that I made and some more I've left for you.

**Items I adjusted in my commits:**

* If Dynamic shape size is odd, the vertices don't line up with the terrain. If the size is not a power of 2, there are gaps at the region boundaries. If the size is too small relative to distance, say 2 and 64, 8 and 256 the whole engine slows down (would be fixed by redesign at bottom). The numbers can get negative or very large. I enforced sane values so they won't break

* Renamed variables and added comments
* Replaced append w/ push_back. They are aliases but the latter is used everywhere else
* Replaced pop_at(i) on negative forloops with pop_back, which is faster. The former recreates the array.
* Stripped camera detection out of update_collision
* Enforced collision setup in build_collision and removed from update_collision
* Changed update calculation time to usec and print it on DEBUG_CONT error level

**There are two other issues I found and have not fixed.**

---------

### Invalid RID
I get this error message multiple times on DYNAMIC_GAME, after running the game, moving the camera, then quitting.

```
ERROR: Invalid ID.
   at: (servers/physics_3d/godot_physics_server_3d.cpp:1619)

or using Jolt:

ERROR: Failed to free RID: The specified RID has no owner.
   at: (src\servers\jolt_physics_server_3d.cpp:1782)
```

This is caused by this code in destroy_collision, 
```
		for (int i = PhysicsServer3D::get_singleton()->body_get_shape_count(_static_body) - 1; i >= 0; i--) {
			RID shape = PhysicsServer3D::get_singleton()->body_get_shape(_static_body, i);
			PhysicsServer3D::get_singleton()->free_rid(shape);
		}
```

This means we can't rely on the server to house the RIDs but must track them ourselves, as we do with `_static_body` and other RID variables. This is typical and expected. The solution is addressed by the redesign below.

-------

### Inefficient Loops

At even the default values for dynamic size/distance with 50-64 shapes in existing, using `existing.has()` to check if the shape is there within 3 for loops means checking: 
* 3 vector integers for each of 64 shapes
* shapes per region squared - default 64
* regions - up to 256

So up to 3 * 64 * 64 * 256 = 3.1 million integer comparisons just to tell if the collision shape already exists. Both the checking if it exists and the overall for loop need to be better designed. We don't need to check for all regions, for all shapes per region x & z, and we don't need to iterate through the array using has.

What should happen in a chunking system is:

**_build_collision**
  * number of shapes needed identified
  * all shapes are created, memory allocated
  * all shapes tracked in three arrays:
    * All shapes - fixed size identified from above
    * Used shapes - fixed size - identified by calculation of distance_size as a grid around camera, some indices are always empty
    * Unused shapes - dynamic size used with push_back / pop_back

**_update_collision**
  * We assume there is a fixed grid where shape locations can be (like an integer grid, or every 4 units, etc)
  * Rather than evaluating all possible points on the grid for all regions, we just take a small area around the camera to evaluate
  * Rather than checking the entire existing array each time, we just translate the grid location to an array index. Then we go directly to that array index and if something is already there, we skip it. This is like how the region offsets work, see `storage.get_region_offset()` and `get_region_index()`. They don't iterate over all regions, they just translate position into an array index. Our _region_map is a fixed size 16x16 array with many empty slots. This isn't the exact code we need, but we need to use the same concept. 
  * Anything unused is disabled and stored in the unused array
  * The only thing that happens in this function is moving shapes between arrays, moving shape locations, and setting vertices. All in a small area around the provided update location. No allocations.

**_destroy_collision**
  * All shapes in our arrays are destroyed without asking the physics server or the tree (children) for them. Fixes the invalid RID problem since we track and free all of our own RIDs, which is our responsibility.

This logic is the same for physics server shapes or instanced shapes. There's very little code difference between the two. The main difference is that we get the RID of the shape and send it to the server, or how shapes are created and destroyed.

This should reduce the update time a bit, but even if not, it's a cleaner design that will help us maintain the code in the future. It won't take much modification from what's already there. But those crucial for loops need to be reworked. I can help you implement this if you like.

2024-02-08 15:30 UTC, TokisanGames commented on src/terrain_3d.cpp
> +							map_data[index] = (Util::is_hole(cmap->get_pixel(shape_global_x, shape_global_z).r)) ? hole_const : map->get_pixel(shape_global_x, shape_global_z).r;
As soon as I switched to Dynamic / Editor running the demo crashes on this line. The camera is outside of the terrain. The reason is:
`get_pixel` is called with `(896, 464)`, however cmap, cmap_x, cmap_xz, cmap_z are all null

Region is currently -1, which means no region. So if region == -1 after line 427, you can skip all of the code down to L558 probably. Though you may want to disable that shape.

2024-02-08 15:42 UTC, TokisanGames commented on src/terrain_3d.cpp
> +							map_data[index] = (Util::is_hole(cmap->get_pixel(shape_global_x, shape_global_z).r)) ? hole_const : map->get_pixel(shape_global_x, shape_global_z).r;
Adding this in L428 is sufficient to have it work. However I haven't looked yet to see if this properly disables the shapes or if it needs to do more.
```
				if (region < 0) {
					continue;
				}

```

2024-02-08 16:00 UTC, TokisanGames commented
I'm going to look at the design a bit more later, but here's some initial testing of functionality.

* It was working very well before, just not the ideal design. Now as it's being redesigned, the issues are normal. Just make sure to not squash your PR yet so we can refer back to commit d720d55f86efeacaf8901e08176e1f0ad2659622 for reference.

* I recently realized the use of `memfree()` in `_destroy_collision()` is wrong. It should be `memdelete()` with `memnew`. `memfree` goes with `memalloc`. Changing these dramatically reduces the number of `RID Allocations leaked at exit` messages when godot closes, which it should. We weren't removing any of them. 

* In Dynamic/editor mode, it seems to be generating only 1/4th of the circle so it doesn't work in game since it's off center.
![image](https://github.com/TokisanGames/Terrain3D/assets/632766/1e47f489-c5f3-44f8-82de-a4db1b20daa7)

* Full / editor mode only generates for the first region.


* On a couple of editor startups I got this error message. Other times it didn't happen. I didn't troubleshoot, so look out for it.
 
```
ERROR: Terrain3D::_update_collision: Collision not initialized, returning
   at: push_error (core/variant/variant_utility.cpp:1091)
```

2024-02-13 20:01 UTC, TokisanGames commented
Note, I fixed the memory leaks for the up coming release.

https://github.com/TokisanGames/Terrain3D/commit/c5115fec2140f5ecff53a0fd11ab6b913e7b28c1

2024-02-19 10:30 UTC, Saul2022 commented
An error i found checking this pr is that  when trying to make play the demo, it doesn´t start and leaves the long messages
 that update coll is not initialized

 core\variant\variant_utility.cpp:1091 - Terrain3D::_update_collision: Collision not initialized, returning

![editor_screenshot_2024-02-19T112621](https://github.com/TokisanGames/Terrain3D/assets/97898580/f1a8de28-409f-4c6e-ba25-bb8a5e1aa2e4)

2024-03-10 07:37 UTC, TokisanGames commented
My current thinking for the foliage instancer is to generate MultiMeshes in chunks. I will build it off of the chunk infrastructure you're building here. I'll be ready to work on foliage in a week or two, so if this isn't done by then I'll get involved to move it along.

2024-03-27 06:39 UTC, TokisanGames commented
This PR needs address https://github.com/TokisanGames/Terrain3D/issues/341#issuecomment-2022062079, and make sure it works without error when running and quitting without regions.

2024-12-31 15:51 UTC, TokisanGames commented
Rebased and consolidated down to three commits. 1st is the previously identified working commit. It works fine but has some errors on cleanup. 2nd is a first pass rewrite that also seems to work, with errors out of bounds. 3rd is a separation into separate classes, which is currently broken due to changes in the main tree not considered in this branch. Unknown if it works.

Next step is to audit the new design, consolidate the new classes down to 1 or 2, and review and adjust the code.

2024-12-31 19:07 UTC, lw64 commented
@TokisanGames yes, thanks for the rebase! Please give some feedback on the system design and APIs

2025-01-07 22:51 UTC, TokisanGames commented
@lw64 I'll take over this PR and work on it for my next priority. As you requested, I'll give you feedback along the way.

Some notes I have already:

* The number of classes and level of abstraction is good for a project that's going to scale very big, or an academic project. For our needs, pairing that down to 1 or 2 classes will do. The instancer handles its own chunk system all in one function.

* Like Godot code, all the headers will have the same copyright. You are included in Contributors and noted on the front page of the repo and in Authors.

Next I need to understand what changes are made in commits 2 and 3, and what is the best way to structure it.

2025-01-08 16:18 UTC, TokisanGames commented on src/chunk_manager.cpp
> +	_chunk_size = p_size;
This is duplicate code and if it's not already available in the engine, should be put in Terrain3DUtil

2025-01-09 06:24 UTC, TokisanGames commented
We have 5 classes: 3 manager types, 2 chunk types. 

Each derivative class should represent a unique object we will create. So if we were going have chunks for say instances, instance collision, ground collision that might warrant 3 child classes and 1 base class for chunks.

However, one manager could process all of those classes. It would be designed to work with the base chunk so it could handle all child types. I don't see the reasoning for having 3 manager types, and certainly not for having more manager types than managee types (chunks).

The design pattern that would be a better fit for this might be a mixture of the composite and template patterns. Something like this, which is exactly how our ProximityManager is constructed. In this case the manager might move the baseobject, then pass the transform or other data to the object run process which could handle generating ground collision, or generating an MMI, or generating collision for objects in the area. 

```
class Manager {
    std::vector<BaseObject*> objects;

public:
    void registerObject(BaseObject* object) {
        objects.push_back(object);
    }

    void processAll() {
        for (auto o : objects) {
            o->process();
        }
    }
};

class BaseObject {
public:
    virtual void process() = 0;
    virtual ~BaseObject() = default;  // Virtual destructor for proper cleanup
};

class Box : public BaseObject {
public:
    void process() override {
        std::cout << "I'm a box." << std::endl;
    }
};

class Sphere : public BaseObject {
public:
    void process() override {
        std::cout << "I'm a sphere." << std::endl;
    }
};
```

2025-01-09 07:12 UTC, lw64 commented
> However, one manager could process all of those classes. It would be designed to work with the base chunk so it could handle all child types. I don't see the reasoning for having 3 manager types, and certainly not for having more manager types than managee types (chunks).

I went for the most simple approach for the start, which is each type of chunk has its own very simple manager, so simple even that they could be in the same file, and the main logic is in the base manager class.

But I can see a lot of potential for optimization there, and having only one manager instance handling everything can enable quite a lot. Also something to keep in mind is doing more complex chunking for example with quadtrees later.

But I think the most complicated part about having one single manager instance is that each chunk type might have different properties, gras chunks are smaller and have shorter visibility, while tree chunks should be bigger and have very far visibility. I think this is possible though, and could avoid a lot of overhead, since not every manager instance does the same work again and again.

2025-01-09 07:16 UTC, lw64 commented
@TokisanGames and thanks for taking over! :D

2025-01-11 11:12 UTC, TokisanGames commented
The overall hierarchical structure of the later commits isn't bad. I just think it is not a good match for our use case. 

base_chunk would be more useful if we were to have multiple class types derive from it. mesh_chunk, collision_shape_chunk, instancer_chunk, etc, each with their own unique functionality, but also enough shared code like positioning, signal responding, creation, deletion (a lot that is already handled by Node3D).

chunk_manager would be useful if we were to have multiple types of managers with their own unique code, but also a lot of shared code.

I think these many classes might be used more if we were making a chunked terrain. In our case a lot of work is already done by engine classes or the clipmap nature.

In a chunked terrain, a chunk might contain a group of nodes with several mesh instance LODs, a physics body, and a collision shape. It may also have a subscene with the assets at that location. It's a lot of unique functionality not already present in the engine.

What functionality do we need in our chunks?

In the instancer, we store the transforms in a data structure, then we create MMIs and place them on the terrain in a grid. The MMIs are the objects we instance that perform a special function (rendering), hence they are the chunk. We don't need another any other functionality in the chunk beyond what the MMI and it's inherited Node3D and Object classes do, so we don't need another class to contain it.

For collision, the object we want to instance and move around is a collision shape. The only functionality we need is to store the data and move it. You have the chunk molding itself to the heightmap. That functionality can easily be done by the manager. I think either is a fine design choice, but in this case, since forming the shape is the only thing it might do, we might as well have the manager do it so we can make the chunk slimmer and remove the containing class entirely.

So we can get away with an instancer management class that manages its MMIs, and a single collision manager class that manages its collision shapes. Both managers creates, moves, configures, and destroys their chunks, but the amount of code to handle those isn't similar enough that it's worth abstracting into a super class. And the chunks already share abstract code in Node3D and Object, so I don't think we need to wrap them any further. 

This is the direction I'm going to move in. Consolidating the classes into a single manager with the collision shape as a chunk and using the first commit as a guide, since it works very well.

2025-01-25 18:57 UTC, TokisanGames commented
Update: Dynamic / Editor and Dynamic / Game modes are working with the new design. Remaining to do are the static modes.

2025-01-27 22:23 UTC, TokisanGames commented
Size/range have been more constrained and dynamic modes now work with vertex spacing 0.25-100. Editor nodes have been removed from the scenetree.

2025-01-28 20:07 UTC, TokisanGames commented
This PR is ready for testing and a careful code review. I'll work on documentation next while waiting for reviews.

To test:

* All options in the collision group, game modes, collision layers/mask/priority
* Vertex spacing
* All demos
* Editor tests in both editor collision modes
  * Adding/removing regions - should rebuild in full, update in dynamic
  * Sculpting - full ignored, update in dynamic/editor
  * Undo/redo - should rebuild/update
* The bugs found in the tracked tickets in the top post

Download this artifact to test: https://github.com/TokisanGames/Terrain3D/actions/runs/13018553729


Notes:

* collision.update() can be called in any mode to update collision, but will skip dynamic slots in the correct spot. Adding (true) will force all collision to be updated at runtime

* Updating dynamic collision as fast as 60fps while sculpting or making holes with gizmos on costs < 0.1ms CPU time (at 16s/64m). So realtime destruction is feasible now. In fact, I have enabled updating from Terrain3DEditor while sculpting in dynamic / editor mode. I don't know if this is worth keeping, but it's practically free, so maybe.

* All Dynamic shape size/distance combos work. The sliders auto adjust their sizes so non-working ratios are not settable.

* The Edge region fix was reimplemented in 034eae9b929cf59dbe2a0dfa8ec27fc9e300c8b0

2025-01-29 10:39 UTC, Xtarsia reviewed
Tested both Godot and Jolt physics, all modes.

The only error i could find was when using Dynamic/Editor mode, and occasionally getting this:

![image](https://github.com/user-attachments/assets/00b53238-7f30-42f4-807a-2d492580433e)

I was unable to get this to occur in dynamic/game, or other modes.

I think 128m might be a bit on the small side, since when testing earlier 256m with larger tile sizes worked fine, maybe allow the or-greater flag (at the users own risk)?

2025-01-29 10:39 UTC, Xtarsia commented on src/terrain_3d_collision.cpp
> +	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "radius", PROPERTY_HINT_RANGE, "16,128,16"), "set_radius", "get_radius");
Should be Variant::INT ?

2025-01-30 13:42 UTC, TokisanGames commented
> The only error i could find was when using Dynamic/Editor mode, and occasionally getting this:
> `core/templates/sort_array.h:255 - bad comparison function; sorting will be broken`

That line is here:
```
	inline void unguarded_linear_insert(int64_t p_last, T p_value, T *p_array) const {
		int64_t next = p_last - 1;
		while (compare(p_value, p_array[next])) {
			if (Validate) {
				ERR_BAD_COMPARE(next == 0); // <----
			}
```

Which might be called from linear_insert(), unguarded_linear_sort(), or linear_sort(), which are all in class SortArray. This class is used by: 
* Navigation math a-star
* Triangle mesh math
* Scene Tree
* Viewport
* Rendering
* Physics collision solver, shape3d

It's not directly used by Dictionary or Array. It could be something totally unrelated like rendering the gizmos or handling the tree children. I have seen this error before, but I'm not able to reproduce it on demand, even with size/range abuse in game and not. Do you recall if these errors occurred in the editor or in game w/ view collision shapes on or off? Or what size/range you were using?

2025-01-30 14:30 UTC, TokisanGames commented
> I think 128m might be a bit on the small side, since when testing earlier 256m with larger tile sizes worked fine, maybe allow the or-greater flag (at the users own risk)?

I expanded range to 256 and if >128, bump min shape_size to 16.

2025-01-30 14:30 UTC, TokisanGames commented
> I think 128m might be a bit on the small side, since when testing earlier 256m with larger tile sizes worked fine, maybe allow the or-greater flag (at the users own risk)?

I expanded range to 256 and if >128, bump min shape_size to 16.

2025-01-30 17:57 UTC, merged

2025-01-30 17:58 UTC, TokisanGames commented
@lw64 Thanks for your help on this. Finally merged.

2025-01-30 18:16 UTC, JekSun97 commented
I don't quite understand what this does, but from what I understand, it will generate collision around the camera/player, but other creatures in the distance can fall through the terrain?

2025-01-30 18:28 UTC, TokisanGames commented
Other creatures in the distance probably shouldn't be processing and wasting cycles. But if they must, read the docs:
https://terrain3d.readthedocs.io/en/latest/docs/collision.html#enemy-collision

2026-03-05 18:02 UTC, jordanmichaelrushing commented
@TokisanGames what about multiple local players and multiple computer players. Thinking specifically a racing game where there is couch versus with computer players. Is this setup to handle dynamic multi humans and computer players?

I tried setting terrain camera for each player but it seems like it only is targeting the last player that set it. Obviously that's a problem if one player is on one side of the race track and humans/computers are on the other side of the race track. Should I just switch fully to raycasting for humans and computers?

2026-03-05 18:27 UTC, TokisanGames commented
You should use discord or Discussions for unrelated questions. By posting here you've emailed everyone who's ever subscribed on this ticket.

Terrain3D and all clipmap terrains aren't great at split screen. The terrain can only be in one place (the clipmap target) per frame. If the player cameras are spread far, the non-active one will display lower lods and won't match collision. You can increase mesh size to help.

As for calculating physics, you need to either increase the dynamic collision size large enough to cover all players, or use full collision mode, or get_height(), or GPU based raycasting (see get_intersection() code and create your own). Physics raycasting won't solve the issue.

Follow up on discord for gamedev advice unrelated to this development PR.