Moves responsibility of checking texture compatibility to developer.
TokisanGames/Terrain3D pull request #295
Opened 2024-01-06 01:34 UTC by lfxu

Redoing #294. When setting a "New ImageTexture", a valid image of FORMAT_MAX is created. Now logs an error "Expects an actual texture file. See documentation for format suggestions."

2024-01-06 07:32 UTC, TokisanGames commented on src/terrain_3d_texture.cpp
> +		LOG(ERROR, "Expects an actual texture file. See documentation for format suggestions.");
Please change `suggestions` to `specification`.

2024-01-06 07:33 UTC, TokisanGames commented on src/terrain_3d_texture_list.cpp
> +					ERR_FAIL_COND_MSG(alb_format != format, "Albedo textures do not have same format! See documentation for format suggestions");
Please change `suggestions` to `specification.` with period, and repeat below.

2024-01-06 07:35 UTC, TokisanGames commented
Thanks for putting this in another branch. This fixes the crashing problem. This issue remains:

* When inserting a non-DXT5/RGBA8 image, then adding a subsequent texture, the texturing breaks when the new texture slot is created because the system generates a texture with DXT5/RGBA w/ mipmaps. The new texture already matches the previous texture size. It also needs to match the format.

2024-01-06 07:36 UTC, TokisanGames requested changes
Thanks for putting this in another branch. This fixes the crashing problem. This issue remains:

* When inserting a non-DXT5/RGBA8 image, then adding a subsequent texture, the texturing breaks when the new texture slot is created because the system generates a texture with DXT5/RGBA w/ mipmaps. The new texture already matches the previous texture size. It also needs to match the format.

2024-01-06 09:01 UTC, lfxu commented
I did some investigation. The actual cause is:
1. Clicking the plus sign to add a texture triggers `_update_texture_data()` without triggering `_is_texture_valid()`.
2. `alb_tex.is_valid()` is false in `_update_texture_data()`, but only on the first call. If you add another texture the second texture `alb_tex.is_valid()` is true. This shows the checkerboard texture is created after `_update_texture_data()` is called.

2024-01-06 09:56 UTC, lfxu commented
Thanks for clarifying. By "the system generates" I thought Godot did that.

Looks like there is not a straightforward way to convert an image to a specified format. One will have to deal with `CompressMode` etc. I also found https://github.com/godotengine/godot/issues/79932. At this point, it is starting to feel impractical / not worth it at this point. Creating a blank texture seems feasible enough though.

2024-01-06 10:38 UTC, TokisanGames commented
This only occurs in the editor, so that ticket is not a concern.
If the first texture exists, you can get its format then create an image with that same format.
The only challenging part is if its a compressed format. You could have a list of compressed formats, and if it's in that list, you can use the compression function. It should work fine for 80-90% of texture types. 

If they have a rare compressed texture that godot can't create, then they'll get an error and a broken display until they drop in a new texture, which is acceptable since it will happen in a small subset of rare textures people will only use <1% of the time.

2024-01-07 18:23 UTC, TokisanGames commented
Updated the PR after a lot more testing. Thanks!

2024-01-07 18:23 UTC, merged