Implements vertex spacing (mesh density)
TokisanGames/Terrain3D pull request #296
Opened 2024-01-06 02:13 UTC by lfxu

Implements #131. In this implementation, only vertex spacing changes. The terrain shape remains unscaled.

Opted for naming "vertex spacing" because it has the least ambiguity.

2024-01-06 06:51 UTC, TokisanGames commented
If this doesn't scale the overall terrain size, then it means 1px != 1 vertex, and we're losing detail. Also I don't see it changing the collision shape at all.

Turn on debug collision so you can see it. It needs to be pixel perfect.

2024-01-06 10:52 UTC, Saul2022 commented
Where is the option at? i built it from source, with your branch and it doesn´t seem to appear neither in the mesh or the renderer section.

2024-01-07 02:17 UTC, lfxu commented
Rendering and editor are now scaled. Navigation and collision todo.

2024-01-07 04:08 UTC, lfxu commented
Navigation and collision should now work too. Let me know if anything is still missing.

2024-01-07 04:55 UTC, lfxu commented
> Where is the option at? i built it from source, with your branch and it doesn´t seem to appear neither in the mesh or the renderer section.

It's in the mesh section, under LOD and size. Make sure you replace the right files in your project and restart Godot.

2024-01-10 11:33 UTC, Saul2022 commented
Tested ( now after  finally being able to make it build after fail and error)  and it works as expected, the terrain  m scales by it double when changing from for instance, 1 to 2, even with multiple regions it seem´s to work well.

2024-01-16 11:35 UTC, TokisanGames requested changes
Thank you for this. I tested it and it works well with collision, navigation, and occlusion. Good job so far! This is a highly requested feature. Here are some issues I found.

* The cursor decal disappears at some angles and heights, and the current tool doesn't work or is offset from the decal at different angles and locations. I tested and found these issues with both 0.5 and 2.0. Use the height brush on the demo and you'll see it disappear above a certain height. Rotate the camera around and add new regions to see it.

* Please explain in detail the changes you made to the shader.

* The normals are off. The first image here has a directional light facing directly down. Here the mesh has a scale of 1.

![image](https://github.com/TokisanGames/Terrain3D/assets/632766/18bddf31-6ffe-468f-91d0-92baa51fc1f8)

Here is a different section where the mesh is scaled at 10. I sculpted it to have a similar height and slope as the other. With the light straight down it should look like the above.

![image](https://github.com/TokisanGames/Terrain3D/assets/632766/26464fd1-1cc2-4294-aead-2fa2acac7bbc)

2024-01-16 11:35 UTC, TokisanGames commented on src/terrain_3d.cpp
> +	ADD_PROPERTY(PropertyInfo(Variant::FLOAT, "mesh_vertex_spacing", PROPERTY_HINT_RANGE, "0.5,50,0.5"), "set_mesh_vertex_spacing", "get_mesh_vertex_spacing");
Please change the range to `"0.25,10.0,0.05,or_greater"`

2024-01-16 11:35 UTC, TokisanGames commented on src/terrain_3d.h
> +	float _mesh_vertex_spacing = 1;
Change all uses of `float` to `real_t`, except where it must be a 32-bit float (control map) and the shaders. Even where it doesn't matter like this small value. And format literals like `1.0f` for assignment, elsewhere they can just be `1.0`. All literals should have a decimal so they are visually apparent.

2024-01-16 11:35 UTC, TokisanGames commented on src/terrain_3d.cpp
> +void Terrain3D::set_mesh_vertex_spacing(float p_spacing) {
clamp it to sane values like 0 and 100.

2024-01-22 06:37 UTC, lfxu reviewed
Issues should be fixed now. Please take a look.

2024-01-28 13:37 UTC, TokisanGames commented
* These new commits change the behavior dramatically. In main, we currently have 1px == 1 vertex and 1 vertex == 1m.

Before these commits, it scaled the terrain laterally, changing only the latter ratio: 1v != 1m, and keeping the first equation, which was my expectation.

After these commits, now both equations are variable. 1px != 1 vertex and 1 vertex != 1m. The problem with this is we have a 1024x1024 height data, but with a vertex spacing of 2. So, we are ignoring 75% of the height data and wasting memory. We need to maintain 1px == 1 vertex.

So this does "fix" the normals issue, but only by not doing any scaling.


* When I build the demo and adjust vertex spacing, it changes the region gizmo size, but they no longer line up with the sculpted area. At 0.25, the region gizmos indicate a very small region space, but the actual regions with sculpted data haven't moved.
![image](https://github.com/TokisanGames/Terrain3D/assets/632766/523b778b-5696-4d41-b5cc-a87355f9573f)

2024-01-28 15:08 UTC, TokisanGames commented on src/shaders/main.glsl
> +varying flat vec3 v_camera_pos;
Why is this flat?

2024-01-28 15:13 UTC, TokisanGames commented on src/terrain_3d_material.h
> +	real_t _mesh_vertex_spacing = 1;
1.0f

2024-01-28 15:25 UTC, TokisanGames commented on src/terrain_3d_material.cpp
> +	RS->material_set_param(_material, "_mesh_vertex_density", (real_t)1.0f / p_spacing);
I don't think (real_t) is needed here. if p_spacing is a double the literal will be promoted to a double for free. Float or double will match the appropriate Variant constructor, which gets converted back to a float anyway.

2024-01-28 15:29 UTC, TokisanGames commented
Thanks for fixing the highlighted issues. Please address the individual inline notes I mentioned, as well the following and I'll merge it in:

* Fix region grid and vertex grid in debug_views.glsl, and any other usages of UV/UV2.
* Restore v_vertex height
* Rebase and resolve conflicts

2024-01-28 21:28 UTC, lfxu commented on src/shaders/main.glsl
> +varying flat vec3 v_camera_pos;
Why is it not? Does view space to world space transform matrix change per vertex?

2024-01-28 22:27 UTC, lfxu commented on src/terrain_3d_material.h
> +	real_t _mesh_vertex_spacing = 1;
Done

2024-01-28 22:27 UTC, lfxu commented on src/terrain_3d_material.cpp
> +	RS->material_set_param(_material, "_mesh_vertex_density", (real_t)1.0f / p_spacing);
Done

2024-01-28 22:27 UTC, lfxu commented on src/shaders/main.glsl
> -		v_vertex = (MODEL_MATRIX * vec4(VERTEX, 1.0)).xyz;
Done

2024-01-29 08:13 UTC, TokisanGames commented
Ok, found a few more errors.

* Decal wasn't scaling. I fixed it.
* New slope sculpting doesn't pick the correct heights. At vertex spacing 1, use the slope sculpting brush, pick a peak, pick a plane, it makes a ramp. Repeat and the ramp gets stronger. 
  * At larger spacing, the higher peak decreases in height each iteration. It should stay the same. 
  * At smaller spacing, the higher end increases in height.
  * The flatten brush height picker seems fine.
* Detecting the mouse cursor has an odd hiccup at some camera angles, when scaling is above 1. Set to 2 or more, use the color map to paint red, pick a flat area and start making vertical streaks and you'll see it jump.


https://github.com/TokisanGames/Terrain3D/assets/632766/5a80ae42-1338-4dbb-8b86-2f429f8a1626

2024-01-29 08:20 UTC, TokisanGames commented on src/shaders/main.glsl
> +varying flat vec3 v_camera_pos;
I wasn't really familiar with it. I see it disables interpolation, not truncates to integer, which is what it sounds like. So why not also make v_vertex and v_vertex_dist flat? All of the varyings we're using currently are there to provide fixed vertex data.

2024-01-30 03:31 UTC, lfxu commented
These don't seem introduced by this PR.
1. The slope tool always decreases a little bit. This is on `main`.
2. Drawing has a gap at distance, in a round shape, due to a branch in `editor.gd` https://github.com/Toki
sanGames/Terrain3D/blob/b95f7f81646ccb98f9611bef9ce7da62d3057c41/project/addons/terrain_3d/editor/editor.gd#L126.

See the reproductions on `main`.
[draw.webm](https://github.com/TokisanGames/Terrain3D/assets/16812130/8c35bf45-7c99-478a-b2ae-94acc0d6c8a1)
[slope.webm](https://github.com/TokisanGames/Terrain3D/assets/16812130/32973c34-df48-4f94-8d19-7a7ca1fd7d94)

These issues should be addressed elsewhere.

A real issue though is the slope decals are at wrong locations. I fixed them.

2024-01-30 10:36 UTC, TokisanGames commented
The slope sculpting was still broken due to mouse_global_position.y also being scaled when it shouldn't have been. That's now fixed.

I also made all of the varyings flat.

The mouse cursor jump can be addressed in #121.

This is ready to go. Great work. Thank you!

2024-01-30 10:37 UTC, merged

2024-01-31 04:12 UTC, lfxu commented
Thanks!