UV rotation & scale painting
TokisanGames/Terrain3D pull request #365
Opened 2024-05-01 12:32 UTC by Xtarsia

de-tiling improvements as well.

Currently
5bit angle, 11.5 degrees, 360.
3 bit scale, 20 scale step, 

Toggles for scale/uv on/off in both Roller and Spray.
Seperate brush for just UV painting, with both toggles as well.

Feedback appreciated!

(will do Doc update later depending on feedback)

2024-05-06 03:23 UTC, TokisanGames requested changes
First of all, thanks for making this a reality. It's mostly working well and will be fantastic once completed.

* Why 5 bits instead of 4 bits? That leaves us 3 bits instead of 4 remaining, which might be used for paintable slope. Witcher3 uses 3 bits for slope. However, that last 1-2 bits might be usable for enabling a water or a non-destructive layer. 
A clock only has 12 segments. 3 bits gives us 16. Do we really need 32?

![image](https://github.com/TokisanGames/Terrain3D/assets/632766/6e02ec41-45db-422a-af05-69de526d498d)


* I first looked at rotating with the checkerbox pattern. It seems there are some subtle artifacts. Top at 0, Lower at 90.

![Godot_v4 2 2-stable_win64_7kOkTbcyL0](https://github.com/TokisanGames/Terrain3D/assets/632766/cec8b066-3fd8-48cc-a989-278db73eeca1)

Here is 180 where the circle outline is now wreathed in the artifact.

![image](https://github.com/TokisanGames/Terrain3D/assets/632766/43ee840a-c883-4033-9b97-77952cf7e984)
Other angles like 45 are strange. I would expect to see the whole pattern rotated at 45 degrees. Doing this with rock might look fine, but with cobblestone it will look like a broken pattern. 

![image](https://github.com/TokisanGames/Terrain3D/assets/632766/d11d4199-5040-40f4-916e-3e0179c336b6)

If it's impossible to get what I (and users will expect) when reading "angle", we might have to change the name of angle and rotation to something that doesn't sound like a pure rotation. Also, if we're not going to get a pure rotation, then giving rotation 5 bits doesn't make any sense. Since it's going to just be rotation-like changes, 16 angles should be just as usable as 32 angles.

* Note I have some changes in `tool_settings.gd` coming this week, so one of us will need to merge with the other depending on which comes first.

https://github.com/TokisanGames/Terrain3D/pull/340/files#diff-d23e039311b38cc86aa4c8470bad9f826e1bd79cea0a4b9caf5b3c65fb56cde5

* Using the per texture uv_rotation as a detiling option is looking great for the first time ever! I've always hated that option, but now it's looking great.

2024-05-06 03:23 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/toolbar.gd
> +	add_tool_button(Terrain3DEditor.UV, Terrain3DEditor.REPLACE, "UV Rotation & Scale", load(ICON_REGION_ADD), tool_group)
Let's remove the UV tool and instead use the `enable` setting for the Paint/Spray brush to enable painting texture, so each has Enable Texture, Enable Angle, Enable Scale. Then it can operate exactly the same as the UV tool just by turning off texture.

Don't worry about the verbose labels. In another PR we'll clean up the labels so it's more concise like this:

Brush, Size, [x] Texture, [x] Angle 0-180, [x] Scale 0-10

For now, yours can look like this:
Brush, Size, [x] Enable, [x] Enable Angle Angle 0-180, [x] Enable Scale Scale 0-10

FYI in my branch, the foliage brush has a lot of UI submenus with additional options and adjustments coming.

2024-05-06 03:23 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/toolbar.gd
> +	add_tool_button(Terrain3DEditor.UV, Terrain3DEditor.REPLACE, "UV Rotation & Scale", load(ICON_REGION_ADD), tool_group)
However, you could put in another option for filter by selected texture. That way it will only paint/scale/rotate if the underlying texture matches the currently selected `texture_id`. Maybe call it `[x] Selected Only`.

That's been a requested feature for the color map as well, which might be out of scope but fine if you're interested.

2024-05-06 03:23 UTC, TokisanGames commented on src/shaders/main.glsl
> +vec2 rota_scale_uv(vec2 uv, vec2 uv_pivot, float scale, int mat_id, float control_angle){
Does "rota" mean anything in particular? I'd prefer to spell out rotate.

2024-05-06 03:23 UTC, TokisanGames commented on src/terrain_3d_editor.cpp
> +					std::array<uint32_t, 8> scale_align = { 5, 6, 7, 0, 1, 2, 3, 4 };
Please write a comment as to what these numbers mean.

2024-05-06 10:45 UTC, TokisanGames commented on project/addons/terrain_3d/editor/components/tool_settings.gd
> +	SEPERATOR,
Actually, I have a better solution coming in https://github.com/TokisanGames/Terrain3D/pull/367 that will be merged soon, so you can remove all of the separator stuff.

2024-05-07 01:50 UTC, TokisanGames commented
Oh, another thing that we'll really need is adding rotation and scale pickers like we have for height/color/roughness.

2024-05-07 17:06 UTC, Xtarsia commented on src/shaders/main.glsl
> +vec2 rota_scale_uv(vec2 uv, vec2 uv_pivot, float scale, int mat_id, float control_angle){
completley reworked, its "uv_detiling()" now.

2024-05-07 17:07 UTC, Xtarsia commented on project/addons/terrain_3d/editor/components/toolbar.gd
> +	add_tool_button(Terrain3DEditor.UV, Terrain3DEditor.REPLACE, "UV Rotation & Scale", load(ICON_REGION_ADD), tool_group)
Removed the UV tool, and built as suggested!

the filter might have to wait, but it is a good idea.

2024-05-07 18:03 UTC, Xtarsia commented
hopefully ive not missed / broken anything. some very minor artifacts remain for edge cases, but I dont think resorting to texturegrad/additional sampling is worth it.

I found 4 bits to be very noticable when trying to paint a curved path, 5bits was enough.

Picker is in too!

2024-05-10 15:42 UTC, Xtarsia commented
`weight = sqrt(weight);`

removing this improves the worse edge case artifacts quite a lot
with:
![image](https://github.com/TokisanGames/Terrain3D/assets/69606701/7013bcd5-ff80-4896-9978-c236590da042)
without:
![image](https://github.com/TokisanGames/Terrain3D/assets/69606701/1a93d213-8442-4234-9f3e-8a5c735d712c)

smoothstep present for both (a general improvement regardless)

2024-05-13 21:24 UTC, Xtarsia commented
Final commit has no artifacts at all, implementing textureGrad with only a single call to each dFdx() and dFdy() functions in coarse mode.

overall enableing full rotation and detiling isnt free, but not too far from it.

shame that the bilinear blend wasnt enough to cover the derivative errors at mid range.

There may be some decent perf gains yet to be had, but thats out of scope for this.

2024-05-23 11:03 UTC, TokisanGames commented on src/shaders/main.glsl
> +	float[8] scale_array = {0.5,0.4,0.3,0.2,0.1,0.8,0.7,0.6};
Is this index 0-4 for positive values, index -1 to -3 for scale reduction?

2024-05-23 11:11 UTC, Xtarsia commented on src/shaders/main.glsl
> +	float[8] scale_array = {0.5,0.4,0.3,0.2,0.1,0.8,0.7,0.6};
Yes.

2024-05-23 20:28 UTC, TokisanGames commented
Really amazing work.

* I reorganized the UI.

![image](https://github.com/TokisanGames/Terrain3D/assets/632766/fabced41-4ec8-4b17-90a5-19e990d8dbca)

* I added a separate enabled_texture for paint/spray so it could have a unique label, until we can expand the tool settings to allow something like that.
 
* I don't think you have the clang hooks installed. When I changed the C++, clang complained and fixed code you modified:

![image](https://github.com/TokisanGames/Terrain3D/assets/632766/88c8ad91-f4c8-4ece-a713-3ae024d33c00)

* I also applied this style to your shader code, placing spaces around operators.

* Oh wow, the painted scale and angle affect the autoshader. Cool.

* We need some debug views for visualizing the scale and autoshader by color. We can do a separate PR so I can merge this. Maybe also finalizing #322 and limiting all options based on existing texture.

2024-05-23 20:29 UTC, merged