Change Terrain to use separate files for each region.
TokisanGames/Terrain3D pull request #374
Opened 2024-05-10 07:06 UTC by SlashScreen

Resolves #356 , and expands terrain limit from 256 to 2048.

2024-05-10 09:28 UTC, TokisanGames commented on src/terrain_3d_storage.h
> +	void load_directory(String p_dir);
duplicate, probably from rebasing

2024-05-10 09:28 UTC, TokisanGames commented on src/terrain_3d_storage.h
> +	String _format_region(int p_i);
duplicate

2024-05-10 09:29 UTC, TokisanGames commented on src/terrain_3d_storage.h
> +	String _format_region(int p_i);
Also, only use `i` for a for loop. Otherwise give variables full names. If this is a region id, then call it `p_region` or `p_region_id`

2024-05-10 09:30 UTC, TokisanGames commented on src/terrain_3d_storage.h
> +	class Terrain3DRegion : public Resource {
duplicate

2024-05-10 09:30 UTC, TokisanGames commented on src/terrain_3d_storage.cpp
> +	ClassDB::bind_method(D_METHOD("get_color_map"), &Terrain3DStorage::Terrain3DRegion::get_color_map);
duplicate

2024-05-10 09:32 UTC, TokisanGames commented on src/terrain_3d_storage.cpp
> +#include <godot_cpp/classes/reg_ex_match.hpp>
can be removed

2024-05-10 09:33 UTC, TokisanGames commented on src/terrain_3d.h
> +	String _storage_directory;
You can expose this with getters, setters, and get it into the inspector.

2024-05-10 09:40 UTC, TokisanGames commented on src/terrain_3d_storage.cpp
> +		Ref<Terrain3DRegion> region = ResourceLoader::get_singleton()->load(files[i]);
region is a fine variable name here. But elsewhere in the code we often use region when referring to the region id. We should rename a lot of regions used as ids to region_id. For sure in this PR you should use region_id when referencing an int.

2024-05-10 09:42 UTC, TokisanGames commented on src/terrain_3d_storage.cpp
> +		LOG(ERROR, "Error saving region at ", fname);
`"saving region file: ", fname, ". Error code: ", ERROR);`

2024-05-10 09:58 UTC, TokisanGames commented on src/terrain_3d_storage.cpp
> +		// 2 - parse coordinates
Turn this into a function, `Vector2i get_region_file_offset()`. you could return `Vector2i(INT32_MIN, INT32_MIN)` if invalid.

2024-05-10 10:03 UTC, TokisanGames commented on src/terrain_3d_storage.h
> +	String _format_region(int p_i);
`_format_region` is better named `get_region_filename(int p_region)` and it can be public and exposed to gdscript as users might want to use it.

save_region and load_region should both exist and public.

I'm not sure yet if it makes more sense to save by region_id or by location or both. For sure loading by location or region offset, as region is not known before loading and changes. Locations and region_offsets are fixed.

load_region and load_directory might share code, possibly the latter calling the former.

2024-05-11 06:34 UTC, TokisanGames commented on src/terrain_3d.h
> +	String _storage_directory;
This isn't resolved. Right now this won't show up in the inspector. You need setters and getters for this and to make a variable in _bind_methods. You need to initiate loading when it changes and emit signals for updating (as is currently done when _storage loads).

2024-05-11 07:09 UTC, SlashScreen commented on src/terrain_3d.h
> +	String _storage_directory;
oops. fixed in latest commit.

2024-05-11 09:03 UTC, TokisanGames commented on src/terrain_3d.cpp
> +	if (_storage.is_null()) {
is_empty()

2024-05-11 09:03 UTC, TokisanGames commented on src/terrain_3d.cpp
>  	ADD_PROPERTY(PropertyInfo(Variant::OBJECT, "storage", PROPERTY_HINT_RESOURCE_TYPE, "Terrain3DStorage"), "set_storage", "get_storage");
Remove this. We don't want to load it.

2024-05-11 09:05 UTC, TokisanGames commented on src/terrain_3d.cpp
> +	ADD_SIGNAL(MethodInfo("storage_directory_changed"));
I think we can keep storage_changed for now. Just emit it when the directory changes instead of this one.

2024-05-13 12:23 UTC, TokisanGames commented on project/terrain/terrain3d_-01-01.res
We don't need the first underscore.

2024-05-14 11:47 UTC, TokisanGames requested changes
Thanks for working on this. 

Here's what I'm thinking we'll do for upgrades:
* Terrain3DRegionManager:Object is the new version of Storage that you're working on.
* Terrain3DStorage:Resource will be a deprecated class with all of the bound functions.
* Storage calls will be redirected to RegionManager so user code won't change. But user's scene files will as the storage resource will stop being saved.
* A `Setup Wizard...` button above the storage directory will appear that will guide users to select their old data file, and the new directory, so we can split the files.
* In a future version, once users no longer have Storage as a resource saved in their scenes, we will rename RegionManager:Object back to Storage:Object. Once again their code won't change.

So you could get started on a setup wizard.tscn and a button in the inspector. It should include:
* "This version of Terrain3D uses separate storage files; one for each region. Select your old storage file below, and the directory where you'd like save the new files so we can convert your data."
* "File names include the region coordinates for convenience. So an old storage file like: `world.res` can instead be changed to `world/terrain3d_01_03.res`, `world/terrain3d_01_04.res`. Positive coordinates are represented by underscores (_), negatives by hyphens (-)."
* Old Storage resource file: [xxxxx]
* New Storage Directory: [xxxxxx]
* [x] Hide SetupWizard for this project (Project settings)
* [x] Hide SetupWizard for all projects (Editor settings)
* Cancel, OK

Here's are some issues I found while testing:

* Upon loading the node demo, I clicked the file directory, created a new blank folder, and accepted it. The existing regions did not clear. They are still there.
  * Then I saved and Godot crashed. On the filesystem, one file is there terrain_-01-01.res. Which looks like the correct size.

* I removed one of the four regions and saved. All 4 files show in the filesystem panel. However, when I restarted, the region is gone. I see the file is removed in windows. I think you need to unload/unref the resource so godot closes it.

* I removed all regions and it did in the display, but it did not remove one file:
`Terrain3DStorage#1768:remove_region: Failure to remove region file at res://terrain/terrain3d__00-01.res`
  * When I restarted, that one file loaded again.

* I added a region, then removed it before saving and got this error:
`Terrain3DStorage#1825:remove_region: Failure to remove region file at res://terrain/terrain3d__06_00.res`
 
* I dragged in the Player and World scenes and can get it to play with 49 regions. 50 and up starts to produce vulkan errors. These might be bugs out of scope for this PR. However it does load them all in the editor, so maybe not.

* I tweaked the importer.gd script (adding: `var storage: Terrain3DStorage`) and upon importing it reported `ERROR: Terrain3DStorage#7944:import_images: Storage not initialized`

2024-05-14 11:47 UTC, TokisanGames commented on src/terrain_3d_storage.h
> +	const String REGION_FORMAT = ".res"; // This was for debugging
.res can be hard coded where used

2024-05-14 11:47 UTC, TokisanGames commented on src/terrain_3d_storage.cpp
> +}
Just use `force_update_maps()` instead of writing a new one.

2024-05-14 11:47 UTC, TokisanGames commented on src/terrain_3d_storage.cpp
> +	return "terrain3d_" + x_str + y_str + REGION_FORMAT;
first underscore is unnecessary

2024-05-14 11:47 UTC, TokisanGames commented on src/terrain_3d_storage.cpp
> +	return "terrain3d_" + x_str + y_str + REGION_FORMAT;
first underscore is unnecessary

2024-05-14 11:47 UTC, TokisanGames commented on src/terrain_3d_storage.cpp
> +
I'm not convinced we need this in storage. Set storage should probably just stay in Terrain3D, which can call `storage->load_directory()`. _storage_directory isn't being saved in this class since Storage is no longer a resource. I think the variable and set/get functions can be removed. And storage has only load/save.

2024-05-14 11:47 UTC, TokisanGames commented on src/terrain_3d_storage.cpp
> +	Ref<Terrain3DRegion> region;
add logging

2024-05-14 11:47 UTC, TokisanGames commented on src/terrain_3d_storage.cpp
> +	if (p_region_id < 0) {
`|| >= _region_offsets.size()`

2024-05-14 11:47 UTC, TokisanGames commented on src/terrain_3d_storage.cpp
> +void Terrain3DStorage::load_region_from_offset(Vector2i p_region_offset) {
add logging

2024-05-14 11:47 UTC, TokisanGames commented on src/terrain_3d_storage.cpp
> +	if (region_id < 0 || region_id >= _region_offsets.size()) {
This will conflict with some changes I made, which you'll find when you rebase. I suggested we should do this, but it's not necessary in this PR.

2024-05-15 23:42 UTC, SlashScreen commented on src/terrain_3d_storage.cpp
> +	if (region_id < 0 || region_id >= _region_offsets.size()) {
So what should I do here?

2024-05-16 10:07 UTC, TokisanGames commented
>> I removed one of the four regions and saved. All 4 files show in the filesystem panel. However, when I restarted, the region is gone. I see the file is removed in windows. I think you need to unload/unref the resource so godot closes it.
> I haven't figured out how to solve this.

Are you using force rebuild or clear?

Use debug logging and get the log when removing a region. Then look at the debug log using the main branch when removing a region. What's the difference? Notepad++ or diff can easily compare two files. You should have logging in all of your new functions.


>> I dragged in the Player and World scenes and can get it to play with 49 regions. 50 and up starts to produce vulkan errors. These might be bugs out of scope for this PR. However it does load them all in the editor, so maybe not.
> Vulkan is out of my wheelhouse. If it's an issue with me, I may not be able to fix it.

How many regions can you run the game with on your computer? What about in the main branch? If your branch has no issue, they should be the same.


>> I tweaked the importer.gd script (adding: var storage: Terrain3DStorage) and upon importing it reported ERROR: Terrain3DStorage#7944:import_images: Storage not initialized
> That makes sense; I think it's trying to instantiate a terrain storage that's designed to be a singleton, so what you're doing is actually incorrect. Variables should probably be defined as var storage:Terrain3DStorage = null. The real issue is that it should give you that message that you need to get the singleton through Terrain3D. I'm not sure how to do that.

You're right, adding that one line didn't fix the import script. It also needs something like:
```
		if not storage:
			#storage = Terrain3DStorage.new()
			storage = get_storage()
```

You should fix this script in this PR. 

> you need to get the singleton through Terrain3D

Instance, not singleton. Only Terrain3D can be used as a singleton.

2024-05-18 07:44 UTC, SlashScreen commented
- Fixed the filesystem issue. The reference issue made no sense to me, so I first pursued the simpler avenue of the filesystem simply needing to refresh. Turns out that's what it was.
- Indeed, Godot seems to slow to a crawl and eventually crash when adding a million terrains. Not only that, it crashed my graphics card too, causing it to reboot. I've experienced similar crashes before; It was caused by lots of data being transferred between the GPU and CPU (I think). I think that terrain3d may have swamped the bandwidth. This will have to wait until texture streaming becomes a thing, I think.

2024-05-19 01:56 UTC, SlashScreen commented
My computer can handle about 130 regions before crashing.

2024-05-21 03:51 UTC, SlashScreen commented
The only outstanding things I can think of are:
- There's a TODO in the importer.gd I left because I wasn't sure how to clear the region manager (since before, it simply made a new terrain 3D storage)
- There's still that issue of how many regions can be handled before things start to crash (but my number is different from yours so I'm not sure what's going on)
- Mark Terrain3DStorage class as deprecated

2024-05-21 03:52 UTC, SlashScreen commented
Should clarify that I have now added the wizard.

2024-05-25 02:38 UTC, TokisanGames commented
You've done `git merge` or used gh desktop sync twice in this PR. You should never do either. It creates a messy commit history. Those merges need to be dropped and this properly rebased at some point.

2024-05-25 02:41 UTC, SlashScreen commented
> You've done `git merge` or used gh desktop sync twice in this PR. You should never do either. It creates a messy commit history. Those merges need to be dropped and this properly rebased at some point.

When did I do that? I haven't purposefully done either. This branch hasn't interacted with main, or any other branch, at all since rebasing last week, or whenever that was.

2024-05-25 03:34 UTC, TokisanGames commented
Looks like two weeks ago

![image](https://github.com/TokisanGames/Terrain3D/assets/632766/985c2541-d271-4dde-9837-fcabca848197)
...
![image](https://github.com/TokisanGames/Terrain3D/assets/632766/a703f3ed-309c-4312-a366-e87f8965cd2d)

2024-05-25 18:55 UTC, SlashScreen commented
I have no recollection of doing this... nor do I have any idea how to undo it.

2024-05-30 20:20 UTC, TokisanGames commented
Buttons are possible in the inspector. I'd prefer this over a setup wizard in the menu if we can make it happen.

https://x.com/passivestar_/status/1795886728646975820

2024-07-20 12:20 UTC, TokisanGames reviewed
Thanks for working on this. Here's my review:

* It builds. Good.
* Conflict resolution after rebasing wasn't clean. There are a lot of changes in your PR that shouldn't be there. After doing your best with the conflict resolution, you should have reviewed the changes for the whole PR on github or with git diff and removed things that shouldn't be there. I'll flag some of them as an example.
* On running there's an error in importer.gd due to the above.
* I don't see the region border gizmo when I view gizmos. Some things in my Godot UI have been acting up, so I can't say this PR is causing that. And I don't see any changes that obviously would break that.
* Foliage works but doesn't save. I'm surprised it works.
* You stated at the top of this pr `expands terrain limit from 256 to 2048`, but I don't see any bounds checking to ensure that. The version in main has a hard limit of 16x16 or 256 regions. If this PR is going to expand that limit, it should remove the 16x16 limitations, but put in bounds checking to ensure the number of regions is <= 2048. So if the user wanted to do a straight line they could. I don't know how much of that is out of scope and should be in another PR yet.

Terrain3DRegionManager is a mouthful. I might rename it to Terrain3DData and a `data_directory` or `data_dir`. I'm not sure if we'll migrate back to storage for 1.0 or keep data.

Overall, it's a solid start. You could have improved delivery just by going over your PR commits, recognizing things that shouldn't here and fixing them before a reviewer comes in.

At this point, I'll take this over to polish it up so we can get it merged in. Thanks for your help on this. It has saved me a lot of time.

2024-07-20 12:20 UTC, TokisanGames commented on src/terrain_3d_region_manager.h
> +	static inline const real_t CURRENT_VERSION = 0.842f;
Renaming the file like this presents a challenge where git diff and git hub won't show revisions between the new and old file. I downloaded the terrain_3d_storage.h/cpp from main and ran a diff on them to see what changes you actually made. Looks like your base is very old and is missing a lot of updates. Here it's storage version 0.842 (which was also used in 0.9.1, but it flagged my attention to this problem).

I looked at the differences with:
```
diff -udw --color=always diff/terrain_3d_storage.h terrain_3d_region_manager.h | less
diff -udw --color=always diff/terrain_3d_storage.cpp terrain_3d_region_manager.cpp | less
```

I will have to go through these diffs to review pull out your changes vs the main tree. If I see anything of note, I'll leave an additional comment on the code here.

2024-07-23 02:14 UTC, TokisanGames commented
This PR has another merge in it. Contributors should never merge. I discussed this and demonstrated how to remove it in the live stream.

![image](https://github.com/user-attachments/assets/4fe18ee1-2bb1-44b6-b278-57c5257dc9b7)

2024-07-23 02:17 UTC, SlashScreen commented
AIIIEEEE 
also you added that, didn't you? why is it a merge?

2024-07-23 02:25 UTC, TokisanGames commented
I haven't changed anything yet. Right now I'm working on removing the merge and the conflict resolution errors.

2024-07-23 02:46 UTC, TokisanGames commented on src/terrain_3d.cpp
> +void Terrain3D::set_storage_directory(String p_dir) {
The CPP contents should be in the same order as the header file. These functions need to be resorted.

2024-07-23 11:25 UTC, TokisanGames commented
> First I'll go through and fix the conflict resolution errors.
> Then I'll fix the updates to storage.h/cpp that should be in your region_manager so I can tell what are your changes.
> Then I'll leave comments on your code and start making changes.

I've fixed the conflict errors, removed the merge, and rebased it. I renamed Terrain3DRegionManager back to Terrain3DStorage so we can see your modifications easily. I'll rename it again when we start writing conversion code. 

I've started a todo list in the first post.

2024-07-23 11:56 UTC, TokisanGames commented on src/terrain_3d_editor.cpp
> +			e_regions.append(i);
Apple clang doesn't like size_t (unsigned long) used in append because there is no Variant(unsigned long). Godot has no unsigned int. Converting this to int fixes the issue and may be faster. I have read that there is more code generated by using an unsigned int rather than a signed one, presumably for some compilers and systems.

Also I'm changing append to push_back for consistency with the rest of the code. They are equivalent.

2024-07-23 17:13 UTC, SlashScreen commented
Sorry for the git mess.

2024-07-24 11:42 UTC, TokisanGames commented on src/terrain_3d_storage.cpp
> +	add_region(global_position, maps);
Not sure why these maps are duplicated, nor why the regions are freed. I see that in save() the Terrain3DRegion is created only on saving.

I'm going to change this design quite a bit. We want Terrain3DRegions in memory all of the time. They will retain the modified state, version, and maps. Here we will load the maps and not duplicate them. The same maps will make their way into the main arrays. Both Storage and the Region will reference the same Images. 

I think the regions will also hold on to their current coordinates, and either a deleted state, or the whole object will be dumped into the undo, or both. TBD.

First I'm moving version to the region, and allow each file to be upgradeable. Then I'll move the modified functionality to the object, which won't be saved in the file but will be visible in the inspector.

2024-07-24 12:01 UTC, TokisanGames commented on src/terrain_3d_storage.cpp
> +void Terrain3DStorage::save_region(const String &p_path, const int p_region_id) {
Resources are smart objects. The region can save itself. Storage is already a bit cluttered and has no need to do it. Storage should delegate. This is moving next.

2024-07-24 16:31 UTC, TokisanGames commented on src/terrain_3d_storage.cpp
> +		Ref<Terrain3DRegion> region = ResourceLoader::get_singleton()->load(p_dir + String("/") + files[i]);
load() defaults to cached mode and actually won't load the file off disk if a previous version is still in memory. That's useful for meshes and textures. But for a file editor, it's really bad. We must load by ignoring the cache.

https://docs.godotengine.org/en/stable/classes/class_resourceloader.html#class-resourceloader-method-load

2024-07-25 02:29 UTC, TokisanGames commented on src/terrain_3d_storage.cpp
> +		Ref<Terrain3DRegion> region = ResourceLoader::get_singleton()->load(p_dir + String("/") + files[i]);
Also this will load everything in the directory. Any and all garbage, and more likely other data files like the asset list or textures.

2024-07-25 03:11 UTC, TokisanGames commented on src/terrain_3d_storage.cpp
> +}
load_region isn't used anywhere so I assume it is to fill out the API. However, it relies on region id which doesn't exist until the region is created and stored in _region_offsets. So it could potentially reload a file only. With the discussion on discord, the API will move more towards offsets/locations first.

2024-07-25 07:45 UTC, TokisanGames commented on src/terrain_3d_storage.cpp
> +			_modified[_modified.size() - 1] = false; // Is my logic right here?...
You have a lot of infrastructure throughout this class to manage the _modified array. It's clearly difficult to manage. In the new design, I'm pushing _modified into the region and we'll let the region keep track of if its modified or not. We'll let the OOP structure do the work, rather than maintain this array.

2024-07-26 09:37 UTC, TokisanGames commented
Updates:
* Region maps are no longer duplicated and the originals freed on load. Now what is loaded is retained and are the actual maps we edit and save. 
* Version is saved in each individual file.
* Modified is moved from storage to the region, but isn't fully implemented
* Regions write their own files 
* Save 16-bit setting moved to terrain3d, handling moved to region
* Separated Terrain3DRegion into its own class and file instead of a subclass.
* First pass on API renames, which lets me review the whole class functions and implementation (will be pushed to main)
* Reordered notification handling (pushed to main)

Main things to work on:
* Finish creating and handling persistent Regions
* Polish up modification tracking
* Rework instancer storage
* Rework height tracking for AABBs
* Rework undo
* Adjust the API for more region location focus

2024-08-14 09:43 UTC, TokisanGames commented
Updates:
* Removed regions are marked for deletion, but not removed from disk until saved.
* Only region files that have been modified (or deleted) are saved.
* Height tracking is done per region on edits and Storage accumulates master heights from all regions w/ an optional full per pixel calculation
* API is fairly set I think
* The PR is back to a mostly working state. Next to do are undo/redo and instancer storage

2024-08-18 06:42 UTC, TokisanGames commented
Instancer now stores its data within Terrain3DRegion. It only saves the regions where instances have changed.

2024-08-18 09:41 UTC, TokisanGames commented
Region labels have been implemented
![image](https://github.com/user-attachments/assets/73a1beb7-72e7-4e9e-b02f-050e1a0a2a81)

2024-08-23 08:37 UTC, TokisanGames commented
Undo/redo now works for regions, including adding and removing multiple in one operation. Removed regions are not removed from disk until saved. Even after files are deleted for removed regions, they are still tracked by the undo system. So if they are undone and the regions added, upon save the files are written again.

2024-08-26 06:51 UTC, TokisanGames commented
Update:
* Undo/redo works now for adding/removing regions, adding regions while sculpting, sculpting, texture, color maps.
* Color maps mipmaps are now generated only after editing or loading regions, instead of everytime update_maps is called. (cc @Dekker3D remove 2c61b11e6477143e4e47f45a2ed1672ccbe2d0f4, add fa0d245401ac08b2c166ac6bb417b0978da05489)

Next to do:
* Undo/redo for foliage
* More testing, bug fixing, and clean up
* Conversion
* Documentation

2024-08-26 07:39 UTC, Dekker3D commented
> * Color maps mipmaps are now generated only after editing or loading regions, instead of everytime update_maps is called. (cc @Dekker3D remove [2c61b11](https://github.com/TokisanGames/Terrain3D/commit/2c61b11e6477143e4e47f45a2ed1672ccbe2d0f4), add [fa0d245](https://github.com/TokisanGames/Terrain3D/commit/fa0d245401ac08b2c166ac6bb417b0978da05489))

From just looking at the diff, this looks a lot better! Haven't tested it for edge cases yet. Does it update the mipmap if a region already has a mipmap, but the colour map was changed after?

2024-08-26 07:50 UTC, TokisanGames commented
Whenever the color map is hand edited with Terrain3DEditor, it regenerates the mipmaps. It also generates upon sanitization if missing.

So if a map is inserted with wrong or invalid mipmaps, they won't be updated.

If the colormap is changed with set_pixel, that also won't update mipmaps. That needs to be fixed. Probably best to make an option in force_update_maps, so they can set_pixel in bulk.

2024-08-26 12:44 UTC, TokisanGames commented
I added an option to force_update_maps that allows a user to regenerate all color mipmaps. A user can also easily do it on individual regions they are editing with `region.get_color_map().generate_mipmaps()`.

2024-09-02 08:40 UTC, TokisanGames commented
Foliage undo/redo now works. This PR still likely has some bugs, so it's worth starting having people test and review it to find them. 

Remaining to test here is ensuring the edited area AABB, set height AABB, and get_texture_id() still work, also with undo.

It currently does not upgrade. That is pushed to another PR, along with documentation. 

Test with this artifact:
https://github.com/SlashScreen/Terrain3D/actions/runs/10663538903

Make a new scene and new directory to store data within.

2024-09-03 13:18 UTC, TokisanGames commented
@Xtarsia Fixed those issues. Use this PR for now. The other PR is for the conversion wizard, which I haven't started reviewing yet.
My bounds checker was very wrong. a9e846b. 
It now rebuilds the region map before iterating through it. c3c13f5
And no longer reloads all storage data every time mesh settings are changed e135e9b

**Update**
Edited area AABB seems to work with MMI transforms updating when sculpting. However, I discovered it's broken (in main) at vertex spacing >=2. But Terrain3DObjects doesn't work.

Still need to test height ranges.

2024-09-04 14:04 UTC, TokisanGames commented
Update_height functions seem to properly work on sculpting and undo. Terrain3DObjects also works. Not sure why it didn't work yesterday. So, I think this PR is done enough for wider testing in the main branch. Now I'll work on the conversion PR #476 before merging.

2024-09-08 13:49 UTC, merged