Terrain3DObjects fixes
TokisanGames/Terrain3D pull request #407
Opened 2024-07-02 15:21 UTC by tcoxon

This PR fixes #390 and #391.

- Gizmo errors are fixed by clearing gizmos when the Terrain3D node is deselected.
- Clicking a tool button re-selects the Terrain3D node.
- Terrain3DObjects reconnects when reparented.

The latter may look more complicated than it really is. I took this moment as an opportunity to clean up the script by making use of the new EditorInterface singleton that Godot gained in 4.2. The functional parts are:

1. Using `call_deferred` in `_on_child_entered_tree` to set up signals after Godot has updated the node's transform following reparenting.
2. Some code that moved from `_edit` to `_handles` to fix cut-and-pasting of Terrain3DObjects.

2024-07-03 05:07 UTC, TokisanGames requested changes
Thanks for this update. Here's what I see when testing w/ 4.2.2.

Re: Gizmo errors
* I no longer see them when selecting

Re: Terrain3DObjects

Seems to work, but prints errors

* Terrain3D selected, add Terrain3DObjects node as a child (**I think most users are going to do this, even if by mistake, as it's a natural workflow**)
* Click player, for the location.
* Add sphere mesh
* Reparent the sphere from the player to the terrain3d objects.
It works, but I get this **message**:
```
ERROR: Node not found: "../../../Player" (relative to "/root/@EditorNode@17122/@Panel@13/@VBoxContainer@14/@HSplitContainer@17/@HSplitContainer@25/@HSplitContainer@33/@VBoxContainer@34/@VSplitContainer@36/@VSplitContainer@61/@VBoxContainer@62/@PanelContainer@109/MainScreen/@CanvasItemEditor@9461/@VSplitContainer@9280/@HSplitContainer@9282/@HSplitContainer@9284/@Control@9285/@SubViewportContainer@9286/@SubViewport@9287/Demo/Player/MeshInstance3D").
```
* Reparent Terrain3DObjects to the root node, nothing on player, and it **repeats the same message**.
* Reparent the spheremesh to the root, then back into Objects, and **the message repeats 2x**
* Delete spheremesh and make a new one attached to the root
* Reparent to Terrain3DObjects, works
* Drag to the root node and get **this message**:
```
ERROR: Node not found: "../Terrain3DObjects" (relative to "/root/@EditorNode@17122/@Panel@13/@VBoxContainer@14/@HSplitContainer@17/@HSplitContainer@25/@HSplitContainer@33/@VBoxContainer@34/@VSplitContainer@36/@VSplitContainer@61/@VBoxContainer@62/@PanelContainer@109/MainScreen/@CanvasItemEditor@9461/@VSplitContainer@9280/@HSplitContainer@9282/@HSplitContainer@9284/@Control@9285/@SubViewportContainer@9286/@SubViewport@9287/Demo/Terrain3DObjects/MeshInstance3D").
```

* At one point, I had it erroring, even if I moved the spheremesh to the root, player, root and other nodes without touching Terrain3DObjects
----
* I added some print statements and found that resetting and returning to the earlier step of moving a meshinstance from player to terrain3dobjects continually calls _on_child_transform_changed, long after the change has occurred. Indeed transform_changed_notifier is constantly emitting every frame

-----
* I made a Terrain3DObjects and a MeshInstance3D attached to the root. Moving the mesh around had no issue.
* I moved Objects as a child of Terrain3D, then moved the mesh into it and it started constantly emitting the signal.
* Moving Objects out from under Terrain3D and the signal stopped. Also it doesn't produce the error. Seems the reparent errors and signal spam occur only if Terrain3DObjects is a child of Terrain3D, which as I mentioned is likely going to be common.

2024-07-03 05:07 UTC, TokisanGames commented on project/addons/terrain_3d/src/ui.gd
> +	plugin.select_terrain()
This is unnecessary now. UI is only visible if the editor plugin is visible, which only happens now if Terrain3D is selected. Before the toolbar showed up when a Terrain3DObject was selected, and this would have been useful then. However your change to editor.gd:_handles no longer makes the toolbar visible on Terrain3DObjects.

2024-07-03 13:23 UTC, tcoxon commented
```
ERROR: Node not found: "../../../Player" (relative to "/root/@EditorNode@17122/@Panel@13/@VBoxContainer@14/@HSplitContainer@17/@HSplitContainer@25/@HSplitContainer@33/@VBoxContainer@34/@VSplitContainer@36/@VSplitContainer@61/@VBoxContainer@62/@PanelContainer@109/MainScreen/@CanvasItemEditor@9461/@VSplitContainer@9280/@HSplitContainer@9282/@HSplitContainer@9284/@Control@9285/@SubViewportContainer@9286/@SubViewport@9287/Demo/Player/MeshInstance3D").
```

These errors aren't anything to do with Terrain3D or Terrain3DObjects. Reparenting meshinstances can break the "skeleton" NodePath. It's an engine/editor bug, although I can't find the issue ID to reference atm. You can get the same errors if you use just a standard Node3D without the Terrain3DObjects script.

> Seems the reparent errors and signal spam occur only if Terrain3DObjects is a child of Terrain3D, which as I mentioned is likely going to be common.

I had a look. It seems like Terrain3D is setting its transform every frame, which propagates down to its child nodes. If you reparent Terrain3DObjects to anything else you can see that the transform_changed signal only emits when the node moves. I think it's a bug - I'll add a fix to my PR.

2024-07-05 08:15 UTC, TokisanGames approved these changes

2024-07-05 08:15 UTC, merged