Channel Packer improvements
TokisanGames/Terrain3D pull request #471
Opened 2024-08-28 18:24 UTC by Xtarsia

Mipmap and Quality options
Luminance as Height
Invert Smoothness
Image Resizing
DDS file type support
normal alignment fix

2024-08-28 19:17 UTC, Xtarsia commented
added width and height to each texture.

when resize is enabled, textures provided for packing no longer need to be the same size.

2024-08-31 08:01 UTC, Xtarsia commented
This is ready for review!

2024-09-11 09:12 UTC, TokisanGames requested changes
Great job. Thanks for improving this. Here are some notes:

* Sometimes generating the height texture and packing produces DXT1, no alpha. This happened after selecting a texture for the height slot, then generating a height texture. In fact, closing the window doesn't reset it. I have to restart the project and generate to get any texture with alpha.

* Please use _gui_input() to close the popup on Escape. Making it a real popup would include that, but I think you did different settings.

* The generated height is better than the artist provided height sometimes. Which tells me we need to improve the blending options and give a height adjustment in a future PR. #351

2024-09-11 09:12 UTC, TokisanGames commented on project/addons/terrain_3d/src/channel_packer.gd
> -
Two spaces between functions is correct.

2024-09-11 09:12 UTC, TokisanGames commented on project/addons/terrain_3d/src/channel_packer.gd
> +		plugin.get_editor_interface().get_resource_filesystem().scan()
EditorInterface

2024-09-11 09:12 UTC, TokisanGames commented on project/addons/terrain_3d/src/channel_packer.gd
> +	var sum:Color = Color(0,0,0,0)
Spaces after : and , on both lines, maybe decimal points too

2024-09-11 09:12 UTC, TokisanGames commented on project/addons/terrain_3d/src/channel_packer.gd
> +	sum -= Color(1,1,1)
spaces and decimals

2024-09-11 09:12 UTC, TokisanGames commented on project/addons/terrain_3d/src/channel_packer.gd
> +	normal_vector = Vector3(sum.r,sum.g,sum.b).normalized()
spaces

2024-09-11 09:12 UTC, TokisanGames commented on project/addons/terrain_3d/src/channel_packer.gd
> +	var mat3:Basis = _alignment_basis(normal_vector)
space :

2024-09-11 09:12 UTC, TokisanGames commented on project/addons/terrain_3d/src/channel_packer.gd
> +			return 1
return FAILED

2024-09-11 09:12 UTC, TokisanGames commented on project/addons/terrain_3d/src/channel_packer.gd
> +		return 1
Return OK and Failed

2024-09-11 09:12 UTC, TokisanGames commented on project/addons/terrain_3d/src/channel_packer.gd
> +			return 1
Return FAILED

2024-09-11 09:12 UTC, TokisanGames commented on project/addons/terrain_3d/src/channel_packer.gd
> +	p_invert_smooth: bool, p_align_normals : bool, channel_to_pack: int) -> int:
Return type Error

2024-09-13 01:01 UTC, Xtarsia commented
Rebased, all reviewed points addressed.

window now closes on ESC.

The error im looking into a bit more.

2024-09-14 14:03 UTC, merged

2024-09-14 14:03 UTC, TokisanGames commented
Great work, thank you!