Subdivide LOD1 and higher
TokisanGames/Terrain3D pull request #482
Opened 2024-09-06 17:37 UTC by Xtarsia

Makes distant LOD levels look much better with a minimal Triangle count increase, so much so that useing half the mesh size yields visually similar results, as seen in this comparison:

mesh size 32 (LOD set to 7):
https://cdn.discordapp.com/attachments/1065519581013229578/1281661402955644938/image.png?ex=66dc87b2&is=66db3632&hm=729d196a0a29e5e5054662480ac2f90e06bbd787f04da94e81268b5c0d550953&

original, mesh size 64 (LOD set to 6):
https://cdn.discordapp.com/attachments/1065519581013229578/1281661403970797679/image.png?ex=66dc87b2&is=66db3632&hm=deda52686236dfde78edcf3e5632cec88922991e1fc586f1fb8f92e9e6150520&

Also, maintains 1:1 with current collision generation
https://cdn.discordapp.com/attachments/1065519581013229578/1281662371206660259/image.png?ex=66dc8899&is=66db3719&hm=bdb8587b449cfb4f3731439cdc8c6b0ff0026f553366246f46e278fb6b9d9545&

2024-09-12 11:47 UTC, TokisanGames commented
I tested this a bit, took video and analyzed the footage. I think this is a good improvement. Maybe we'll look at it again if we switch to a symmetric grid but for now I like what is going on.

The full mesh @ 64 before was 741k vertices. 
The new mesh @ 32 is 345k, with a 10-20% speed improvement.
The new mesh @ 48 is 760k, with a 0-20% speed improvement.

32 is too chunky for my taste. Let's put the demo at the same vertex count, with a 48 mesh size.

The only thing I don't like is the edges of the last LOD get sawtoothed on one side. Can you fix this?

![{DA8ECF8C-0CC4-4E43-8D72-8808B4C22D07}](https://github.com/user-attachments/assets/120ac5c5-6dea-4847-9812-423ed389ebcb)

2024-09-12 12:04 UTC, TokisanGames requested changes

2024-09-12 12:04 UTC, TokisanGames commented on src/geoclipmap.cpp
> +	auto midpoint = [](const Vector3 &p1, const Vector3 &p2) -> Vector3 {
Not a fan of these autos, but looking at the type in MSVC, I suppose they are fine.

2024-09-12 12:04 UTC, TokisanGames commented on src/geoclipmap.cpp
> +static void _subdivide_half(PackedVector3Array &vertices, PackedInt32Array &indices) {
Let's put this and the struct above into the class. No reason to have them floating outside, is there?

2024-09-12 12:04 UTC, TokisanGames commented on src/terrain_3d.cpp
> +				if (l == 0) {
Please change `l` here and above and below to `lod`.

2024-09-12 21:17 UTC, Xtarsia commented
the sawtooth is a result of adding extra vertices at the yellow dots ive marked in this image:

![image](https://github.com/user-attachments/assets/621b75c0-e2e9-4440-905b-8aa08a01b920)

I can't think of a reasonable way to avoid them.

2024-09-12 22:43 UTC, Xtarsia commented on src/geoclipmap.cpp
> +	auto midpoint = [](const Vector3 &p1, const Vector3 &p2) -> Vector3 {
Me either, but I too came to the conclusion that they were fine.

2024-09-12 22:44 UTC, Xtarsia commented
Rebased, review points addressed.

2024-09-13 04:06 UTC, TokisanGames commented
> I can't think of a reasonable way to avoid them.

What about adding the final square edge vertices?

2024-09-13 12:24 UTC, Xtarsia commented
jagged edges will be resolved by #488 😃

2024-09-14 14:16 UTC, merged

2024-09-14 14:17 UTC, TokisanGames commented
Thank you!