modify-brush-alpha-blend-conditions
TokisanGames/Terrain3D pull request #492
Opened 2024-09-16 16:58 UTC by Xtarsia

Changed alpha threshold to 0.5 along with extra conditions to make painting feel a bit more intuitive. 

blending may be a little slower again with the default circle 0 brush, useing circle 1 is similar to before

painting over the auto shader, or painting base onto base, or spray onto spray now follows the percieved brush shape much better.

angle and scale now also much more closley follow the visibility of the selected texture too.

images with height textures that are not centered around 0.5 maybe end up with a small inward, or outward halo for angle/scale values, however this is still an improvement over the entire brush square getting overwritten as it did before this change.

closes #481 tho a pure solution would be seperate values for base/over but that is probably not needed.

2024-10-04 12:15 UTC, TokisanGames commented on src/terrain_3d_editor.cpp
> +				uint32_t dest_id = asset_id;
You could just drop dest_id and only use asset_id. 
asset_id should probably be set const to be safe. 
And put it on the right side of the `if (dest_id == base_id)` on L366

2024-10-04 12:16 UTC, TokisanGames commented
Ok pretty good. Lots of nice improvements here. There are a couple of odd effects that should be looked at though, but overall It's very close to what we want. I like how the tightening of the alpha clamp makes the brush feel more true to the brush shape.

Strength feels good overall. I want every setting to do something. So 1% should never not do anything, and 100% should be fast, but reasonable. Even 1000+% should be a super max, but still clamped to a not insane number. I recently clamped height/slope because 1000% spit out stupid values. Now they are just faster values than 100% but no more than any sane person would want.

I've drawn out all of the cases to pinpoint what currently happens and what should or not happen. I bolded the expected conditions that should change.

The setting in the left column is the only one selected (none, texture, scale, angle).

### Manually painted area
Large section of **painted** grass w/ a strip of **painted** rock

**Paint**
|Setting|Result|Expected
|--|--|--
|Nothing|Nothing|Ok
|Texture|Changes base texture|Ok
|Scale|Changes scale of all textures|Ok, but **filtered by texture is probably better**
|Angle|Changes angle of all textures|Ok, **as above**. See spray scale/angle

**Spray**
|Setting|Result|Expected
|--|--|--
|Nothing|Nothing|Ok
|Texture, selected id == base|Decreases blend|Ok
|Texture, selected id != base|Changes overlay texture, increases blend|Ok
|Scale|Changes scale of selected texture|Ok, expected and good
|Angle|Changes angle of selected texture|Ok, expected and good

### Autoshaded area 
**Paint**
|Setting|Result|Expected
|--|--|--
|Nothing|Nothing|Ok
|Texture|Disables auto, changes base texture|Ok
|Scale|Changes scale| Unexpected, but ok
|Angle|Changes angle|Unexpected, but ok

**Spray**
|Setting|Result|Expected
|--|--|--
|Nothing w/ selected id==base id|Nothing|Ok
|Nothing w/ selected id!= base id|Disables autoshader|**Unexpected, should do nothing**
|Texture|Disables auto, changes spray texture|Ok
|Scale|Changes scale| Unexpected, but ok
|Angle|Changes angle| Unexpected, but ok

### Border of Manual/Autoshaded
|Setting|Result|Expected
|--|--|--
|Spray Texture @10%| Disables autoshader, sprays, slight halo if base is different|Ok
|Spray Texture @5% | Very slowly disables autoshader, then sprays | **A bit weak**
|Spray Texture @4% | Does nothing to autoshader | **Unexpected problem**

This bottom range for disabling the autoshader should move down 4% so the current 5% is the new 1%.

2024-10-04 12:16 UTC, TokisanGames requested changes
Ok pretty good. Lots of nice improvements here. There are a couple of odd effects that should be looked at though, but overall It's very close to what we want. I like how the tightening of the alpha clamp makes the brush feel more true to the brush shape.

Strength feels good overall. I want every setting to do something. So 1% should never not do anything, and 100% should be fast, but reasonable. Even 1000+% should be a super max, but still clamped to a not insane number. I recently clamped height/slope because 1000% spit out stupid values. Now they are just faster values than 100% but no more than any sane person would want.

I've drawn out all of the cases to pinpoint what currently happens and what should or not happen. I bolded the expected conditions that should change.

The setting in the left column is the only one selected (none, texture, scale, angle).

### Manually painted area
Large section of **painted** grass w/ a strip of **painted** rock

**Paint**
|Setting|Result|Expected
|--|--|--
|Nothing|Nothing|Ok
|Texture|Changes base texture|Ok
|Scale|Changes scale of all textures|Ok, but **filtered by texture is probably better**
|Angle|Changes angle of all textures|Ok, **as above**. See spray scale/angle

**Spray**
|Setting|Result|Expected
|--|--|--
|Nothing|Nothing|Ok
|Texture, selected id == base|Decreases blend|Ok
|Texture, selected id != base|Changes overlay texture, increases blend|Ok
|Scale|Changes scale of selected texture|Ok, expected and good
|Angle|Changes angle of selected texture|Ok, expected and good

### Autoshaded area 
**Paint**
|Setting|Result|Expected
|--|--|--
|Nothing|Nothing|Ok
|Texture|Disables auto, changes base texture|Ok
|Scale|Changes scale| Unexpected, but ok
|Angle|Changes angle|Unexpected, but ok

**Spray**
|Setting|Result|Expected
|--|--|--
|Nothing w/ selected id==base id|Nothing|Ok
|Nothing w/ selected id!= base id|Disables autoshader|**Unexpected, should do nothing**
|Texture|Disables auto, changes spray texture|Ok
|Scale|Changes scale| Unexpected, but ok
|Angle|Changes angle| Unexpected, but ok

### Border of Manual/Autoshaded
|Setting|Result|Expected
|--|--|--
|Spray Texture @10%| Disables autoshader, sprays, slight halo if base is different|Ok
|Spray Texture @5% | Very slowly disables autoshader, then sprays | **A bit weak**
|Spray Texture @4% | Does nothing to autoshader | **Unexpected problem**

This bottom range for disabling the autoshader should move down 4% so the current 5% is the new 1%.

2024-10-04 18:17 UTC, Xtarsia commented
Things should behave more consistently now.

the case where spray did nothing at all, was related to this clamp:
``real_t spray_strength = CLAMP(strength * 0.05f, 0.003f, .25f);``

since 1/255 is 0.0039 if the value was between 0.003 and 0.0039 then blend would never accumulate over time.

setting the minimum to 0.004 resolved that.

i've added additional cases to make dealing with the auto shader more consistent too. whilst painting angle/scale seemed ok, it always ended up feeling a bit off to me, since the conditions would be based on the invisible state of the base/over/blend.

2024-10-06 11:00 UTC, TokisanGames commented
Added filtering to color and wetness to fix #192. However, we aren't doing a weighted blend on the colormap, so if the color is too contrasted, it will get blocky.
![Image](https://github.com/user-attachments/assets/aaa16444-2810-4219-9187-83a0f7e5a73c)
![{54629409-E6AC-42C7-ACBC-888CD6CC76A6}](https://github.com/user-attachments/assets/6b660bac-696b-4afa-b872-e40381e0b9b9)

2024-10-06 11:09 UTC, merged

2024-10-06 11:09 UTC, TokisanGames commented
Great, thank you!