control map api changes
TokisanGames/Terrain3D pull request #494
Opened 2024-09-17 22:54 UTC by Xtarsia

2024-10-02 09:39 UTC, TokisanGames commented on src/terrain_3d_data.h
> +	uint8_t base = uint8_t(CLAMP(p_base, 0.f, 31.f));
This should be an integer clamp, not float. Maybe the uint8_t should cast the 0 and 31 instead of the result as well, otherwise we might cast twice.

2024-10-02 09:46 UTC, TokisanGames commented on src/terrain_3d_data.h
> +	set_control(p_global_position, (control & ~(0x7 << 7)) | enc_uv_scale(uvscale));
According to the docs this should be `(x & 0x7) <<6`. 7 matches util.h. So the docs are wrong.

2024-10-02 09:58 UTC, TokisanGames commented on src/terrain_3d_data.h
> +	return real_t((get_control(p_global_position) >> 14 & 0xFF)) / 255.f;
Out of bounds, get_control will return UINT32_MAX. This will return 1.0. NAN might be better.

2024-10-02 09:59 UTC, TokisanGames commented on src/terrain_3d_data.h
> +}
If global_position is out of bounds, get_control will return UINT32_MAX, set_pixel will error with "no region". That's fine.

2024-10-02 10:00 UTC, TokisanGames commented on src/terrain_3d_data.cpp
> +real_t Terrain3DData::get_control_scale(const Vector3 &p_global_position) const {
get_control_scale/angle could be moved to the inline functions so they're all together. Also I note that these two are written in a different style than the others (eg using get_pixel instead of get_control, which is inlined but has extra stuff)

2024-10-02 10:02 UTC, TokisanGames commented on src/terrain_3d_data.h
> +	uint8_t overlay = uint8_t(CLAMP(p_overlay, 0.f, 31.f));
integer clamp

2024-10-02 10:15 UTC, TokisanGames commented on src/terrain_3d_data.h
> +	return (get_control(p_global_position) >> 1 & 0x1) == 1;
Hmm, what do we do about out of bounds for these? False I guess.

2024-10-02 10:17 UTC, TokisanGames commented on src/terrain_3d_data.h
> +	return (get_control(p_global_position) >> 1 & 0x1) == 1;
Let's reorder these the same as bit order or descending as is here. Hole, navigation, auto.

2024-10-02 10:21 UTC, TokisanGames commented on src/terrain_3d_data.h
> +inline void Terrain3DData::set_control_auto(const Vector3 &p_global_position, const bool p_auto) {
Let's reorder these in the same order as the control map format doc; descending bit order. Set before get. In the declaration and definition.

2024-10-02 10:28 UTC, TokisanGames commented on src/terrain_3d_data.cpp
> +	ClassDB::bind_method(D_METHOD("set_control_overlay", "global_position", "id"), &Terrain3DData::set_control_overlay);
How about texture_id instead. And blend_value or blend instead of just value.

2024-10-02 10:28 UTC, TokisanGames commented
Thank you. The API is fine. If you rebase it, I can generate the XML and add in a commit so you can at least put in the return values. I'll fill out the rest.

2024-10-02 10:30 UTC, TokisanGames requested changes
.

2024-10-04 10:12 UTC, TokisanGames commented on src/terrain_3d_data.h
> +	return (get_control(p_global_position) >> 1 & 0x1) == 1;
This still isn't correct. Out of bounds we get UINT32_MAX.
UINT32_MAX >> 1 = 0111 1111 1111 1111... 1111 & 0001 == 1

2024-10-04 10:18 UTC, TokisanGames commented
Auto/nav/hole need another adjustment. I added XML. You could fill out the description or at least return values and I'll wrap up anything left.

2024-10-04 10:21 UTC, Xtarsia commented on src/terrain_3d_data.h
> +	return (get_control(p_global_position) >> 1 & 0x1) == 1;
Ah, I should add the same ternery for these then too.
uint32_t control = get_control(p_global_position);
return control == UINT32_MAX ? false : is_auto(control);

though.. when we are useing all control bits, is it not possible that UINT32_MAX is the correct stored value in some situations?

2024-10-04 10:22 UTC, TokisanGames commented on src/terrain_3d_data.h
> +	uint8_t blend = uint8_t(CLAMP(Math::round(CLAMP(p_blend, 0.f, 1.f) * 255.f), 0.f, 255.f));
Aren't these clamps redundant? I don't think there's any value p_blend could be where the inner clamp makes a difference.

2024-10-04 10:24 UTC, Xtarsia commented on src/terrain_3d_data.h
> +	uint8_t blend = uint8_t(CLAMP(Math::round(CLAMP(p_blend, 0.f, 1.f) * 255.f), 0.f, 255.f));
Yep, you're right.

2024-10-04 10:29 UTC, TokisanGames commented on src/terrain_3d_data.h
> +	return (get_control(p_global_position) >> 1 & 0x1) == 1;
Technically possible, but that means there's a hole there. It also means the the autoshader is on and overlay is 100% blended and base id is hidden. So, we could disallow base and overlay to be 31 when blend is 1. Base could reset to id 0 if it becomes a problem.

2024-10-04 12:53 UTC, Xtarsia commented
Hopefully ready for @TokisanGames to apply that final bit of polish now..

2024-10-04 14:38 UTC, TokisanGames commented
Very good, thank you.

2024-10-04 14:38 UTC, merged