Compatibility renderer support
TokisanGames/Terrain3D pull request #500
Opened 2024-09-25 20:05 UTC by Xtarsia

Detects whether Godot is using the compatibility renderer.

If so,
The generated shader will have a set of #defines added that allow full support for the standard shader.
The shader override will also contain these defines, only if generated when in compatibility.

The editor will inject code at the begining, and the end either the standard shader, or any provided override shader
in order to draw a "decal" on the terrain.

in the interest of simplicity, the gdscript changes are as small as possible, tho some things are a bit inneficient,
performace is fine and its only during editing anyways.

The slope tool doesnt have propper decal support.

adding terrain3d.get_compatibility() seems a bit dubious to me, but saved repeating a ton of code in gdscript, and ensures that the editor is always on the same page.

Finally, there are no warnings at the moment when the albedo and normal arrays are in compressed mode. for 4.3 this is fixed anyways, but for 4.2 all textures will be black. The workaround is to re-import all textures as "Lossless".

a test version is available: https://github.com/Xtarsia/Terrain3D/actions/runs/11040148246

2024-09-26 05:44 UTC, TokisanGames commented on src/terrain_3d_material.cpp
> +	_compatibility = p_compatibility;
Since get_compatibility is public, let's drop the parameter and do this:
`_compatibility = _terrian->get_compatibility()`

2024-09-26 05:44 UTC, TokisanGames commented on src/terrain_3d.h
> +	bool get_compatibility() const { return _compatibility; };
Maybe `is_compatibility` is more consistent

2024-09-26 05:46 UTC, TokisanGames commented on src/terrain_3d.h
> +	bool _compatibility = false;
This should probably be in the `//Rendering` section

2024-09-26 05:51 UTC, TokisanGames commented on src/shaders/compatibility.glsl
> +// expects UV.
Does this mean UV (0-region_size in region space), not UV2 (0-1 in local space), and not world space? We should define these in the shader design md doc so I'm not confused again.

2024-09-26 05:55 UTC, TokisanGames commented on src/shaders/gpu_depth.glsl
> -// Mobile renderer HDR mode has limit of 1 or 2. Pack full range depth to RG
This first part about the mobile HDR mode is still true and good to keep somewhere, maybe where the depth texture is actually read. I don't know why I wrote 1 or 2 like I didn't know :/  . I'm sure there's a similar limit for compatibility.

2024-09-26 06:02 UTC, TokisanGames commented on src/shaders/gpu_depth.glsl
> +
In my notes I have these options:
* `ALBEDO = vec3(depth_linear); // Absolute value for Forward+ HDR` since the HDR viewport can have any 16-bit value
* The encoded version to fit it within the mobile HDR range
* And this to get the world position instead of depth:
```
	float depth = textureLod(depth_texture, SCREEN_UV, 0.).x;
	vec3 ndc = vec3(SCREEN_UV * 2.0 - 1.0, depth);
	vec4 world = CAMERA * INV_PROJECTION_MATRIX * vec4(ndc, 1.0);
	vec3 world_position = world.xyz / world.w;	
	ALBEDO = world_position;
```

2024-09-26 06:09 UTC, TokisanGames commented on src/terrain_3d_material.cpp
> +	// inserted at the end of the shader
It's a very small, nitpicking thing, but I'd prefer comments start with a capital. I usually leave off the periods if it's one line, but use them if it's a paragraph. It's so small, but it reminds me of Steve Jobs demanding the inside of macs and iphones look nice too. On an open source project, we're literally building a tool for people to look at the inside of, and we are building a beautiful tool. The work you've done here is fantastic and appreciated by everyone.

2024-09-26 06:19 UTC, TokisanGames commented on src/terrain_3d_material.cpp
> +	}
Maybe this beginning section should go before the end section? 

Doesn't this find `shader_type spatial;` and you probably want it after `render_mode blend_mix,depth_draw_opaque,cull_back,diffuse_burley,specular_schlick_ggx,skip_vertex_transform;`?
`p_shader.find(";", p_shader.find(";") + 1) + 1`?

Though it could come after `*/` since we should always have a /* */ comment at the top. And our comments above the raw string in main.glsl should note that the first */ and last } in fragment are sentinels.

2024-09-26 06:22 UTC, TokisanGames commented on src/shaders/compatibility.glsl
> +//INSERT: EDITOR_SETUP_DECAL
Though this is only for compatibility now, we're eventually going to use it for everything. And it is an editor function inserted differently than compatibility defines above. So maybe this block should be placed in `editor_functions.glsl` now.

2024-09-26 06:26 UTC, TokisanGames requested changes
Very nice. This is a good one.  ~~to be our 500th PR!~~ (_edit_: oh # 500 means our 500th document including issues and discussions. This is our... 144th PR)

I added a note that it will fix a ticket.

Please also try exporting the demo to webgl. I reviewed code but haven't tested it yet. I'll also test the export.

You can also add some notes to platform.md that it is now supported, and what they need to do for 4.2 and 4.3. And any notes for WebGL as well.

I thought you said 4.2 must use '(vram) uncompressed' before. Here you say 'Lossless'. Do both work? Whichever does, make sure to get the exact name for the documentation and our discord guidance.

2024-09-26 07:59 UTC, Xtarsia commented on src/shaders/compatibility.glsl
> +// expects UV.
clarified this comment, its actually texture uv in world space.

2024-09-26 08:21 UTC, Xtarsia commented on src/shaders/compatibility.glsl
> +//INSERT: EDITOR_SETUP_DECAL
makes sense, moved EDITOR_SETUP_DECAL to editor_functions.glsl

2024-09-26 08:31 UTC, Xtarsia commented on src/shaders/gpu_depth.glsl
> -// Mobile renderer HDR mode has limit of 1 or 2. Pack full range depth to RG
If i remember rightly, Forward+ is 16bit, mobile is 10bit and compatibility is 8bit.

however compatibility has a strange color space conversion that trims blacks, and causes some values between 8 and 127 to sometimes be rounded up or down to the nearest even number, which was causeing havok with the depth encode.

this didnt occur in the top half of the range. Thankfully, using effectivly 7 bits of all 3 color channels is still more than enough, and works perfectly for all 3 render modes.

comment updated with some more info!

2024-09-26 08:35 UTC, Xtarsia commented on src/shaders/gpu_depth.glsl
> +
I thought about encoding position, but there just isnt enough bits to hold xyz, it could be possible to pass just the y component instead.

2024-09-26 08:39 UTC, Xtarsia commented on src/terrain_3d.h
> +	bool _compatibility = false;
I thought about that, but decided not to initially as all the variables in that section are represented in the inspector.

i'll leave that decision to you.

2024-09-26 08:42 UTC, Xtarsia commented on src/terrain_3d_material.cpp
> +	// inserted at the end of the shader
I'm all for correcting any typos / grammar / spelling / formatting etc. iv'e missed!

2024-09-26 08:43 UTC, Xtarsia commented on src/terrain_3d_material.cpp
> +	}
I've swapped the order round, and changed to insert just before vertex(). inserting too early meant no access to uniforms or functions from later on in the shader!

2024-09-26 09:50 UTC, TokisanGames commented on src/terrain_3d.h
> +	bool _compatibility = false;
Yes, please move it down. You categorized the function there as well

2024-09-26 11:20 UTC, Xtarsia commented
Im unable to get web export working, i suspect due to needing custom export template build for terrain 3D, or something along those lines.

As for textures import settings for 4.2, both options work.

I'll add some initial things to platform.md in the mean time.

2024-09-27 17:05 UTC, TokisanGames commented
* In compatibility mode, the minimum.gdshader complains about fma, even though it isn't connected to anything. I had to comment it out.

* Here are my notes on getting webgl working. It isn't successful yet.

### Docs
Building instructions
https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_web.html

Godot Export for web docs
https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_web.html

### Building

To build the extension for web you must install emscripten, set up the build environment, then build the web assembly version. I installed with scoop, which is how my python is also installed, per the Godot building instructions. 

```
$ scoop install emscripten
# then I restarted my terminal to get the updated path to finish installing emscripten

$ emsdk install latest
$ emsdk activate latest

# finally setup the build environment
$ source ~/scoop/apps/emscripten/current/emsdk_env.sh
$ scons platform=web target=template_debug

$ ls project/addons/terrain_3d/bin/*.wasm
project/addons/terrain_3d/bin/libterrain.web.debug.wasm32.wasm
```

### Exporting

* Select [custom dlink unthreaded template](https://forum.godotengine.org/t/gdextension-not-loading-in-web-export/81867/5), which I found here: `C:/Users/Cory/AppData/Roaming/Godot/export_templates/4.3.stable/web_dlink_nothreads_debug.zip`
* Vram compressed textures don't work for me on Edge. They don't load in the log. They stop complaining with VRam uncompressed.
* Export and web load reports this message, but [tickets have said](https://github.com/godotengine/webrtc-native/issues/136#issuecomment-1918640657) we can ignore that.
```
ERROR: No suitable library found for GDExtension: res://addons/terrain_3d/terrain.gdextension. Possible feature flags fe
   at: (./editor/plugins/gdextension_export_plugin.h:129)
```

### Upload to Webserver
After export, the full package must be uploaded to a webserver. Itch or your own. That server must be configured with SharedArrayBuffer & Cross Origin Isolation.
In nginx this can be enabled with:
```
    location ^~ /terrain3d/ {
        add_header "Cross-Origin-Opener-Policy" "same-origin";
        add_header "Cross-Origin-Embedder-Policy" "require-corp";
    }

```
On Itch.io , edit game, find the Embed Options section and enable:

`SharedArrayBuffer support - (Experimental) This may break parts of the page or your project. Only enable if you know you need it.`


### Running

I built w/ 4.2.2 and seemed to mostly load but error messages complained that my scene files were built for 4.3?? So I built and exported everything with 4.3: godot source, godot-cpp, Godot binary, Godot export templates.

Edge complained about being unable to load the textures if compressed with vram compressed. But no complains using vram uncompressed.

Currently it loads to the godot logo, then a grey screen. The javascript console reports this:
![{047F5A68-6253-4B55-B5FD-8F977D9C0DCB}](https://github.com/user-attachments/assets/75b515b8-deec-4e42-a3bc-10b0ec9ab266)

2024-09-27 17:19 UTC, TokisanGames commented
* Nice work. Aside from webgl, it works well. It even stutters just like I remember in Godot 3. :/

* The lack of visual indication for the slope tool is a problem. Drawable is not intuitive without it. If you don't already know how it works it will be easy to be confused by it. What can we do about this?

* Figuring out how to build for web won't hold this PR or release up.

* It renders very differently. Brighter, stronger normals, half the speed.

![image](https://github.com/user-attachments/assets/7257194c-85bd-4033-8301-caeb3b60aecd)

2024-09-27 20:13 UTC, TokisanGames commented on src/terrain_3d_material.cpp
> +	idx = shader.find("void vertex() {") - 1;
They could code like a neanderthal and write: `void  vertex ( )  {` or worse:
```
void vertex()
{
// do cave man shading
}
```
Probably best to go with regex:
``` 
var regex = RegEx.new()
regex.compile("void\\s+vertex\\s*\\(")
var result = regex.search(shader)
if result:
	print(result.get_start()) 
```
https://docs.godotengine.org/en/stable/classes/class_regex.html#class-regex

2024-09-27 21:02 UTC, Xtarsia commented on src/terrain_3d_material.cpp
> +	idx = shader.find("void vertex() {") - 1;
I think adding "//SHADER_INJECTION_POINT_VERTEX // do not remove this line. It must be directly before the vertex() function!"

and inserting there would be most straight forwards.

2024-09-27 21:47 UTC, Xtarsia commented on src/terrain_3d_material.cpp
> +	idx = shader.find("void vertex() {") - 1;
the regex wasnt too bad to add, its cleaner from the user side as well.

2024-09-28 09:42 UTC, TokisanGames commented on src/terrain_3d_material.cpp
> +	RegEx regex;
This line crashes Godot for me in 4.3 with a console error:
```
ERROR: BUG: Godot Object created without binding callbacks. Did you forget to use memnew()?
   at: (godot-cpp\src\classes\wrapped.cpp:87)
```
This works:
```
	Ref<RegEx> regex;
	regex.instantiate();
	regex->compile("void\\s+vertex\\s*\\(\\s*\\)[\\s\\n]*\\{");
	Ref<RegExMatch> match = regex->search(shader);
```

2024-09-28 09:44 UTC, TokisanGames commented on src/terrain_3d_material.cpp
> +		shader = shader.insert(idx - 1, "\n" + insert);
idx is already -1 from L172. This is now -2 from "void vertex", when I think it should just be 0. Insert "\nmystuff\n\n" at the "void vertex" 0 position. My original debug view inclusion of inserting -1 before "}" is probably wrong.

2024-09-28 09:57 UTC, TokisanGames commented on src/terrain_3d_material.cpp
> +				_shader_override->set_code(_generate_shader_code().insert(0, _shader_code["EDITOR_COMPATIBILITY_DEFINES"]));
I inserted the minimum shader into the override slot and it dumps an error, then inserts shader defines into my file, above `shader type`. I think it should be after render_mode.

2024-09-29 07:13 UTC, Xtarsia commented
I think I need to tidy up the regex stuff a bit still.

2024-09-29 12:05 UTC, TokisanGames commented
New url. Back tick \` will also capture the mouse, and arrow keys will turn the camera.
https://tokisan.com/terrain3d_demo/demo.html

It seems that all the samplers need highp. Including those in uniforms.glsl.

Here's the full console log, after adding additional highps:
[console_log.txt](https://github.com/user-attachments/files/17179088/console_log.txt)


The last remaining shader error is:
```
demo.js:474  ERROR: 0:528: '[' : array index for samplers must be constant integral expressions
also 535, 536.
```

These lines are:
```
demo.js:459 528: 			vec2 m_decal_uv=(((vec2(((m_cosa * m_uv.x) - (m_sina * m_uv.y)), ((m_sina * m_uv.x) + (m_cosa * m_uv.y))) - (vec2(((m_cosa * m_dus_editor_decal_position[m_i].x) - (m_sina * m_dus_editor_decal_position[m_i].y)), ((m_sina * m_dus_editor_decal_position[m_i].x) + (m_cosa * m_dus_editor_decal_position[m_i].y))) * m_dus_vertex_density)) * m_size) * m_dus_vertex_spacing);

demo.js:459 535: 			float m_decal=smoothstep(0.10000000149012, 1.0, texture(m_dus_editor_decal[m_i], (m_decal_uv + 0.5)).r);
demo.js:459 536: 			m_albedo=mix(m_albedo, m_dus_editor_decal_color[m_i].rgb, (m_decal * m_dus_editor_decal_color[m_i].a));
```

I'm not sure why webgl doesn't like these array indices compared to our other array indices.

> texture(m_dus_editor_decal[m_i], (m_decal_uv + 0.5)).r`
I think this should be `texture(_editor_decal, vec3(decal_uv + 0.5, float(i)))`. In my own custom shader, accessing an array index this way was working, but when I put this into the glsl file and compiled, Godot reported:
`SHADER ERROR: Invalid arguments for the built-in function: "texture(sampler2D[3],vec3)".`

2024-10-02 09:26 UTC, Xtarsia commented on src/terrain_3d_material.cpp
> +		shader = shader.insert(idx - 1, "\n" + insert);
the 1 \n before is warrented, and the -1 aswell to ensure the insert happens before the } as without it, it will insert after the closing brace.

the inserts include a new line anyways.

idx is assigned to the new find value rather than accumulating now anyways.

2024-10-02 16:35 UTC, Xtarsia commented
This PR https://github.com/godotengine/godot/pull/85430 should make correctly determining when to use compatibility modifications much simpler.

2024-10-02 16:36 UTC, TokisanGames approved these changes
Great, thanks for all the updates. I've made a few changes and am squashing now.

2024-10-02 16:46 UTC, merged

2024-10-02 16:46 UTC, TokisanGames commented
Ok, down to 4 clean, topical commits. Thanks for all the work on this. It will help a lot of people.