move cursor decals to shader
TokisanGames/Terrain3D pull request #538
Opened 2024-11-02 01:48 UTC by Xtarsia

removes all decals, closes #534

2024-11-02 08:14 UTC, TokisanGames commented
Great! 

* What do you think about taking care of #533 in this PR as well and adding a larger open crosshair or circle around the cursor when small (or always)?

* Please remove UI.gd:_on_setting_changed():update_decal(). It's annoying to have it popup all the time when changing texture colors. I have it on mine but havn't pushed it yet.

* Why do we need separate decals for the gradients? Are there any ideas or reasons for having a third decal? What do you think if instead of three open slots for textures, we specify them: 0= current brush, 1=ring, 2=crosshair/etc? Then in the shader we can name them such as use them by name rather than editor_decal[0]?

2024-11-02 08:36 UTC, TokisanGames commented on src/shaders/editor_functions.glsl
> +		float fade = clamp((_editor_decal_timestamp - TIME) * 8. - 6., 0., 1.);
What do 8 and 6 represent?

2024-11-02 10:36 UTC, Xtarsia commented on src/shaders/editor_functions.glsl
> +		float fade = clamp((_editor_decal_timestamp - TIME) * 8. - 6., 0., 1.);
As only an offset time stamp is passed each update, those 2 values work with the offset to replicate the timer fade delay & speed of the original decal_timer.

2024-11-02 14:03 UTC, Xtarsia commented
ok im fairly happy with the cross hair now.

size 0;
afar:
![image](https://github.com/user-attachments/assets/0e1731a8-a752-440c-821f-84eb89b9f082)
upclose:
![image](https://github.com/user-attachments/assets/48c42e77-a8e1-4c73-a81e-31334c65aa52)

size 50;
afar:
![image](https://github.com/user-attachments/assets/b0ea0010-d3c7-4e22-8f61-3dd16e9dc06e)
upclose:
![image](https://github.com/user-attachments/assets/80449b27-9962-4d23-bffa-b2be2efd1399)

threshold setting in advanced, defaults to 16
![image](https://github.com/user-attachments/assets/9708c060-e000-46cf-bb09-289420866c2e)

2024-11-02 14:10 UTC, Xtarsia commented
shorter line length feels better
![image](https://github.com/user-attachments/assets/776fc8cf-ab85-44b5-8166-977f03718605)

2024-12-26 04:21 UTC, TokisanGames requested changes
Thanks for working on this. In my review copy I rebased it, then tested.

* crosshair(s) seems to be most widely used as a single word. So all cross_hair references could drop the underscore.
 
* I'd like to see the crosshair lines the same opacity as the brush so they match better. 

* I don't see the fade on timeout, though I see there's code in there. The only way to make it disappear is a single right click, but it reappears when the mouse moves. There are times when the camera is close and the cursor is big, and we want to adjust something in the inspector and see the results on the terrain w/o the decal. Currently the process is to wait until it disappears then adjust. We need either the timeout, or maybe a better alternative is to hide the cursor as soon as the mouse leaves the viewport, or both.

* In this PR, with Paint mode, if you right-click-hold and move the camera, let go (cursor invisible), click-hold and paint, the cursor will appear at a wrong spot and paint, then jump to where it should be and continue painting.

* Comptability mode, Raise 100% strength, white decal Brightness is way too bright. As well as slope, spray, foliage ring. The other colors are acceptable. Forward foliage ring is a bit bright as well.
 
* I'm wondering if the lines should change thickness/size based on the brush size. 🤔 

* Can be rebased and squashed to one commit.

2024-12-26 04:21 UTC, TokisanGames commented on project/addons/terrain_3d/src/ui.gd
> -	update_decal()
Fade on timeout isn't working, but what I believe this did is showed the decal when the brush_size gets larger or smaller. Currently the decal size doesn't change on adjustment.

2024-12-26 04:21 UTC, TokisanGames commented on project/addons/terrain_3d/src/ui.gd
> +		editor_decal_rotation[0] = 0
Please change to 0.

2025-01-03 12:36 UTC, Xtarsia commented on src/shaders/editor_functions.glsl
> +		float fade = clamp((_editor_decal_timestamp - TIME) * 8. - 6., 0., 1.);
Reworked to use a timer and tween, similar to original implementation, this method was not reliable.

2025-01-03 14:37 UTC, Xtarsia commented
> * In this PR, with Paint mode, if you right-click-hold and move the camera, let go (cursor invisible), click-hold and paint, the cursor will appear at a wrong spot and paint, then jump to where it should be and continue painting.

This happens on main too. Its related to get_intersection() GPU mode problems.

2025-01-04 07:28 UTC, TokisanGames commented on project/addons/terrain_3d/src/editor_plugin.gd
> +	# necessarily being a InputEventMouseMotion object. get_intersection() also
> as the mouse position can move without necessarily being a InputEventMouseMotion object

👀🤯

2025-01-04 07:29 UTC, TokisanGames commented
Given the new changes to the shader, these tasks could be addressed, if you're up for it:
* Audit the shader comments where they say `3 lookups` and make sure those are accurate for each section
* Review [shader design](https://terrain3d.readthedocs.io/en/latest/docs/shader_design.html) and offer updates to things that have changed, or new information that would be useful to devs
* Ensure the tip on [adding a custom map](https://terrain3d.readthedocs.io/en/latest/docs/tips.html#add-a-custom-texture-map) is still accurate.

2025-01-04 23:12 UTC, Xtarsia commented
what I wrote in the docs might need some more work.

the last commit is a bit cheeky, but updates the demo textures, and applies some detiling to them. Also made the grass a bit smaller too.

2025-01-07 22:20 UTC, TokisanGames commented on doc/docs/shader_design.md
> +
Like the first side node, this is a potential future improvement that isn't implemented? I can section these two side notes off under a clearer heading, after the line below.

BTW, I'm waiting for you to tell me this PR is ready for another review.

2025-01-08 10:34 UTC, Xtarsia commented on doc/docs/shader_design.md
> +
Hmm this probably could be changed, added it more as another reason to use index map over splat map - it is already implemented.

2025-01-08 17:11 UTC, Xtarsia commented
@TokisanGames Rebased, and hopefully finished.

2025-01-09 17:00 UTC, TokisanGames commented
> fixed derivative rotations

Looks great. Much more stable now.

> added more agressive branching to texture lookups in get_material()

Fantastic

Addressed issues:
* Show decals on modifier presses
* Don't show decal on inspector settings change (eg uv scale), only on tool settings

2025-01-10 12:47 UTC, TokisanGames commented
There are times when I get these errors starting up, closing a scene, or saving the code.

```
SCRIPT ERROR: Invalid assignment of index '0' (on base: 'Array[bool]') with value of type 'bool'.
          at: update_decal (res://addons/terrain_3d/src/ui.gd:321)
SCRIPT ERROR: Out of bounds get index '0' (on base: 'Array[Color]')
          at: @editor_decal_fade_setter (res://addons/terrain_3d/src/ui.gd:63)
```

2025-01-10 12:53 UTC, TokisanGames commented
The size of these arrays is indeed 0. I setup them in _init() and it worked on a first restart. But then I closed one scene and opened another scene and they're reporting size 0 again.

2025-01-10 13:36 UTC, Xtarsia commented
```gdscript
func set_visible(p_visible: bool, p_menu_only: bool = false) -> void:
	editor_decal_color.resize(3)
	editor_decal_position.resize(3)
	editor_decal_rotation.resize(3)
	editor_decal_size.resize(3)
	editor_decal_visible.resize(3)
	terrain_menu.set_visible(p_visible)

```

```gdscript
var editor_decal_fade: float :
	set(value):
		if (editor_decal_color.size() > 0):
			editor_decal_fade = value
			editor_decal_color[0] = Color(
				editor_decal_color[0].r,
				editor_decal_color[0].g,
				editor_decal_color[0].b,
				value
			)
			RenderingServer.material_set_param(mat_rid, "_editor_decal_color", editor_decal_color)
```

this seems to cover enough bases.

2025-01-10 13:50 UTC, TokisanGames commented
I have no issues with these changes. Do you get any errors with just these, and nothing in update_decal?

```python
 var editor_decal_fade: float :
        set(value):
                editor_decal_fade = value
+               if not plugin.terrain:
+                       return
                editor_decal_color[0] = Color(

func set_visible(p_visible: bool, p_menu_only: bool = false) -> void:
                ...
                visible = p_visible
                toolbar.set_visible(p_visible)
                tool_settings.set_visible(p_visible)
+               if editor_decal_color.size() != 3:
+                       # These sizes get reset to 0 on user scene closes. No idea why
+                       editor_decal_position.resize(3)
+                       editor_decal_rotation.resize(3)
+                       editor_decal_size.resize(3)
+                       editor_decal_color.resize(3)
+                       editor_decal_visible.resize(3)

```

2025-01-10 13:58 UTC, Xtarsia commented
Yes, if i have both the demo, and navdemo scenes open at the same time with terrain3d selected in both scenes, switch back and forth, and then close 1, I get errors again until i deselect and reselect the terrain3d node in the remaining scene.

2025-01-10 15:37 UTC, merged

2025-01-10 15:37 UTC, TokisanGames commented
Excellent work as always. Thank you.